import { useState } from 'react'
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card'
import { Badge } from '@/components/ui/badge'
import { getLocale } from '@/paraglide/runtime.js'

type WorkloadKey = 'stateless' | 'stateful' | 'agent' | 'sandbox' | 'bot'

export function CloudflareEdgeMatrix() {
  const isEn = getLocale() === 'en'
  const [workload, setWorkload] = useState<WorkloadKey>('stateful')
  const [bindingMode, setBindingMode] = useState<'binding' | 'rest'>('binding')
  const [sandboxLine, setSandboxLine] = useState<'stable' | 'next'>('next')

  const workloads = {
    stateful: {
      titleId: 'Multiplayer Real-time & Sinkronisasi State',
      titleEn: 'Real-time Multiplayer & State Sync',
      primitive: 'Durable Objects (DO)',
      skill: '/durable-objects',
      wranglerExample: '// wrangler.jsonc (fragment)\n"durable_objects": { "bindings": [\n  { "name": "CHAT_ROOM", "class_name": "ChatRoom" }\n] },\n"migrations": [\n  { "tag": "v1", "new_sqlite_classes": ["ChatRoom"] }\n]',
      role: 'getByName() + SQLite',
      whyId: 'Durable Objects menjamin single-point-of-coordination global dengan penyimpanan SQLite lokal per instance.',
      whyEn: 'Durable Objects provide a guaranteed single point of coordination globally with co-located SQLite storage.',
    },
    stateless: {
      titleId: 'API & Webhook Berkecepatan Tinggi',
      titleEn: 'High-Throughput API & Webhooks',
      primitive: 'Workers Core (V8 Isolates)',
      skill: '/workers-best-practices',
      wranglerExample: '// wrangler.jsonc (fragment)\n"name": "api-gateway",\n"main": "src/index.ts",\n"compatibility_date": "<today\'s date for a new Worker>",\n"observability": { "enabled": true, "traces": { "enabled": true } }',
      role: 'bindings + observability',
      whyId: 'Handler Workers stateless dengan binding untuk akses resource, observability.enabled plus observability.traces.enabled, dan tipe dari wrangler types.',
      whyEn: 'Stateless Worker handlers with bindings for resource access, observability.enabled plus observability.traces.enabled, and types generated by wrangler types.',
    },
    agent: {
      titleId: 'Siklus Nalar Multi-Turn AI Agent',
      titleEn: 'Multi-Turn AI Agent Reasoning Loop',
      primitive: 'Cloudflare Agents SDK',
      skill: '/agents-sdk',
      wranglerExample: 'import { Agent, routeAgentRequest, callable } from "agents"\n\nexport class ResearchAgent extends Agent<Env, State> {}',
      role: 'Agent<Env, State>',
      whyId: 'Agents SDK menyediakan state persisten berbasis SQLite yang disinkronkan lewat setState, method @callable (RPC lewat WebSocket), scheduling, dan integrasi MCP.',
      whyEn: 'The Agents SDK provides SQLite-backed persistent state synced via setState, @callable methods (RPC over WebSocket), scheduling, and MCP integration.',
    },
    sandbox: {
      titleId: 'Eksekusi Kode Untrusted & Sandbox Runner',
      titleEn: 'Untrusted Code Execution & Sandbox Runner',
      primitive: 'Cloudflare Sandbox SDK (@next)',
      skill: '/sandbox-next',
      wranglerExample: '# Dockerfile (image on the same @next line as the package)\nFROM cloudflare/sandbox:next',
      role: 'Cloudflare Containers',
      whyId: 'Lingkungan Linux terisolasi di atas Cloudflare Containers, dikendalikan dari Workers lewat sandbox.exec(argv) yang mengembalikan handle proses.',
      whyEn: 'Isolated Linux environments on Cloudflare Containers, driven from Workers through sandbox.exec(argv), which returns a process handle.',
    },
    bot: {
      titleId: 'Proteksi Form Publik & Anti-Bot',
      titleEn: 'Public Form Protection & Anti-Bot',
      primitive: 'Turnstile + Workers Backend',
      skill: '/turnstile-spin',
      wranglerExample: 'const outcome = await siteverify(token, secretKey, { action, hostname })',
      role: 'siteverify',
      whyId: 'Verifikasi fail-closed di backend: wajib success === true, action yang diharapkan, dan hostname yang diizinkan; token bersifat sekali pakai sehingga replay harus ditolak.',
      whyEn: 'Fail-closed backend verification: require success === true, the expected action, and an allowed hostname; tokens are single-use, so replays must be rejected.',
    },
  }

  const currentWl = workloads[workload]

  return (
    <section id="edge-matrix" className="scroll-mt-20 space-y-6">
      <div>
        <div className="flex items-center gap-2">
          <h2 className="text-2xl font-bold tracking-tight text-balance">
            {isEn ? 'Edge Runtime & Binding Matrix' : 'Matriks Runtime & Binding Cloudflare'}
          </h2>
          <Badge variant="secondary" className="font-mono text-xs">
            Interactive
          </Badge>
        </div>
        <p className="text-muted-foreground mt-1 text-sm">
          {isEn
            ? 'Interactive guide to Cloudflare primitives: pick the right primitive for a workload, compare bindings vs the REST API, and inspect Sandbox package lines.'
            : 'Panduan interaktif untuk primitif Cloudflare: pilih primitif yang tepat untuk beban kerja, bandingkan binding vs REST API, dan periksa lini package Sandbox.'}
        </p>
      </div>

      <div className="grid gap-6">
        {/* Module 1: Architecture Decision Engine */}
        <Card className="border border-border">
          <CardHeader className="pb-3">
            <CardTitle className="text-base font-semibold">
              {isEn ? '1. Edge Architecture & Primitive Decision Engine' : '1. Mesin Keputusan Arsitektur Edge & Primitif'}
            </CardTitle>
            <p className="text-xs text-muted-foreground">
              {isEn
                ? 'Select your application workload to discover the recommended Cloudflare edge primitive and binding.'
                : 'Pilih jenis beban kerja aplikasi Anda untuk menemukan primitif edge dan binding Cloudflare yang direkomendasikan.'}
            </p>
          </CardHeader>
          <CardContent className="space-y-4">
            {/* Workload Buttons */}
            <div className="flex flex-wrap gap-2">
              {(
                [
                  ['stateful', 'Multiplayer & State', 'Multiplayer & State'],
                  ['stateless', 'Stateless API / Webhook', 'Stateless API / Webhook'],
                  ['agent', 'AI Agent Loop', 'Loop AI Agent'],
                  ['sandbox', 'Sandboxed Code Runner', 'Eksekusi Kode Sandbox'],
                  ['bot', 'Anti-Bot / Form Security', 'Anti-Bot / Keamanan Form'],
                ] as const
              ).map(([key, enLabel, idLabel]) => (
                <button
                  key={key}
                  type="button"
                  onClick={() => setWorkload(key)}
                  className={`rounded-lg px-3 py-1.5 text-xs font-semibold transition-colors border ${
                    workload === key
                      ? 'border-primary bg-primary/10 text-primary'
                      : 'border-border bg-card text-muted-foreground hover:text-foreground'
                  }`}
                >
                  {isEn ? enLabel : idLabel}
                </button>
              ))}
            </div>

            {/* Architecture Result Card */}
            <div className="rounded-lg border border-border bg-card p-4 space-y-3">
              <div className="flex flex-wrap items-center justify-between gap-2 border-b border-border pb-3">
                <div>
                  <span className="text-[10px] font-mono uppercase text-muted-foreground block">
                    {isEn ? 'RECOMMENDED PRIMITIVE' : 'PRIMITIF DIREKOMENDASIKAN'}
                  </span>
                  <div className="text-base font-bold text-foreground font-mono">
                    {currentWl.primitive}
                  </div>
                </div>
                <div className="flex items-center gap-2">
                  <Badge variant="outline" className="font-mono text-xs">
                    {currentWl.role}
                  </Badge>
                  <Badge className="bg-primary/20 text-primary border border-primary/30 font-mono text-xs">
                    {currentWl.skill}
                  </Badge>
                </div>
              </div>

              <div className="grid gap-3 md:grid-cols-2 text-xs">
                <div className="space-y-1.5">
                  <span className="font-semibold text-foreground">
                    {isEn ? 'Architecture Rationale: ' : 'Alasan Arsitektur: '}
                  </span>
                  <p className="text-muted-foreground leading-relaxed">
                    {isEn ? currentWl.whyEn : currentWl.whyId}
                  </p>
                </div>
                <div className="space-y-1.5">
                  <span className="font-semibold text-foreground font-mono text-[11px]">
                    Config / Code:
                  </span>
                  <pre className="rounded bg-zinc-950 p-2.5 text-[11px] font-mono text-zinc-200 overflow-x-auto border border-zinc-800">
                    {currentWl.wranglerExample}
                  </pre>
                </div>
              </div>
            </div>
          </CardContent>
        </Card>

        {/* Module 2 & 3 in 2 Columns */}
        <div className="grid gap-6 md:grid-cols-2">
          {/* Module 2: Direct Bindings vs REST */}
          <Card className="border border-border">
            <CardHeader className="pb-3">
              <CardTitle className="text-base font-semibold">
                {isEn ? '2. Worker Bindings vs the Cloudflare REST API' : '2. Binding Worker vs REST API Cloudflare'}
              </CardTitle>
              <p className="text-xs text-muted-foreground mt-0.5">
                {isEn
                  ? 'workers-best-practices flags REST API calls for operations that a Worker binding already provides.'
                  : 'workers-best-practices menandai pemanggilan REST API untuk operasi yang sudah disediakan binding Worker.'}
              </p>
            </CardHeader>
            <CardContent className="space-y-4">
              <div className="flex gap-1.5 bg-muted/60 p-1 rounded-lg border border-border">
                <button
                  type="button"
                  onClick={() => setBindingMode('binding')}
                  className={`flex-1 py-1 text-xs font-mono font-bold rounded transition-colors ${
                    bindingMode === 'binding'
                      ? 'bg-emerald-500/20 text-emerald-600 dark:text-emerald-400'
                      : 'text-muted-foreground hover:text-foreground'
                  }`}
                >
                  {isEn ? 'Worker Binding (Preferred)' : 'Binding Worker (Disarankan)'}
                </button>
                <button
                  type="button"
                  onClick={() => setBindingMode('rest')}
                  className={`flex-1 py-1 text-xs font-mono font-bold rounded transition-colors ${
                    bindingMode === 'rest'
                      ? 'bg-destructive/20 text-destructive'
                      : 'text-muted-foreground hover:text-foreground'
                  }`}
                >
                  {isEn ? 'Cloudflare REST API (HTTP)' : 'REST API Cloudflare (HTTP)'}
                </button>
              </div>

              <div className="rounded-lg bg-muted/30 p-3 border border-border space-y-3 text-xs">
                <div className="text-[11px] text-muted-foreground leading-relaxed">
                  {bindingMode === 'binding' ? (
                    <span className="text-emerald-600 dark:text-emerald-400 font-semibold">
                      {isEn
                        ? '✓ The binding is declared in Wrangler config and reached through env: no REST call, no API token to manage in the Worker. Generate the types with wrangler types.'
                        : '✓ Binding dideklarasikan di config Wrangler dan diakses lewat env: tanpa panggilan REST dan tanpa API token yang dikelola di Worker. Hasilkan tipenya dengan wrangler types.'}
                    </span>
                  ) : (
                    <span className="text-destructive font-semibold">
                      {isEn
                        ? '✕ Adds network and authentication overhead (an HTTP request to api.cloudflare.com with a token). Use it only when no binding exists for the operation.'
                        : '✕ Menambah overhead jaringan dan autentikasi (request HTTP ke api.cloudflare.com dengan token). Pakai hanya bila tidak ada binding untuk operasi tersebut.'}
                    </span>
                  )}
                </div>

                <pre className="rounded bg-zinc-950 p-2 text-[11px] font-mono text-zinc-200 overflow-x-auto border border-zinc-800">
                  {bindingMode === 'binding'
                    ? '// Worker binding (D1 example)\nconst user = await env.DB.prepare(\n  "SELECT * FROM users WHERE id = ?"\n).bind(id).first()'
                    : '// Public REST call\nconst res = await fetch(\n  "https://api.cloudflare.com/client/v4/...",\n  { headers: { Authorization: `Bearer ${TOKEN}` } }\n)'}
                </pre>
              </div>
            </CardContent>
          </Card>

          {/* Module 3: Sandbox Package Line Incompatibility */}
          <Card className="border border-border">
            <CardHeader className="pb-3">
              <CardTitle className="text-base font-semibold">
                {isEn ? '3. Sandbox Package Lines' : '3. Lini Package Sandbox'}
              </CardTitle>
              <p className="text-xs text-muted-foreground mt-0.5">
                {isEn
                  ? 'Stable and @next are separate lines: never mix a Worker package with an image from the other line.'
                  : 'Lini stable dan @next terpisah: dilarang mencampur package Worker dengan image dari lini lain.'}
              </p>
            </CardHeader>
            <CardContent className="space-y-4">
              <div className="flex gap-1.5 bg-muted/60 p-1 rounded-lg border border-border">
                <button
                  type="button"
                  onClick={() => setSandboxLine('stable')}
                  className={`flex-1 py-1 text-xs font-mono font-bold rounded transition-colors ${
                    sandboxLine === 'stable'
                      ? 'bg-amber-500/20 text-amber-600 dark:text-amber-400'
                      : 'text-muted-foreground hover:text-foreground'
                  }`}
                >
                  stable (@cloudflare/sandbox)
                </button>
                <button
                  type="button"
                  onClick={() => setSandboxLine('next')}
                  className={`flex-1 py-1 text-xs font-mono font-bold rounded transition-colors ${
                    sandboxLine === 'next'
                      ? 'bg-primary/20 text-primary'
                      : 'text-muted-foreground hover:text-foreground'
                  }`}
                >
                  @next (@cloudflare/sandbox@next)
                </button>
              </div>

              <div className="rounded-lg bg-card border border-border p-3 space-y-2 text-xs">
                {sandboxLine === 'stable' ? (
                  <div className="space-y-2">
                    <div className="flex justify-between items-center">
                      <Badge variant="outline" className="font-mono text-[10px]">Stable</Badge>
                      <span className="text-[10px] text-amber-600 dark:text-amber-400 font-mono font-semibold">{isEn ? 'Existing apps can stay' : 'Aplikasi lama boleh tetap'}</span>
                    </div>
                    <p className="text-muted-foreground text-[11px] leading-relaxed">
                      {isEn
                        ? 'exec(command) takes a command string and resolves when the command finishes, with buffered stdout/stderr/exitCode; sessions can carry cwd and env across commands. Existing apps can stay here; new projects are recommended on @next.'
                        : 'exec(command) menerima string perintah dan selesai saat perintah selesai, dengan stdout/stderr/exitCode ter-buffer; session dapat membawa cwd dan env antar perintah. Aplikasi lama boleh tetap di sini; proyek baru disarankan memakai @next.'}
                    </p>
                    <pre className="rounded bg-muted p-2 font-mono text-[10px] text-foreground">
                      {'const result = await sandbox.exec("npm test")\n// result.stdout, result.exitCode, result.success'}
                    </pre>
                  </div>
                ) : (
                  <div className="space-y-2">
                    <div className="flex justify-between items-center">
                      <Badge className="bg-emerald-500/20 text-emerald-600 dark:text-emerald-400 border border-emerald-500/30 font-mono text-[10px]">
                        @next (1.0 preview)
                      </Badge>
                      <span className="text-[10px] text-emerald-600 dark:text-emerald-400 font-mono font-semibold">{isEn ? 'Recommended for new projects' : 'Disarankan untuk proyek baru'}</span>
                    </div>
                    <p className="text-muted-foreground text-[11px] leading-relaxed">
                      {isEn
                        ? 'exec(argv) takes an argv list and resolves when the process starts, returning a handle (output(), logs(), waitForExit(), kill()). There is no implicit shell. startProcess is a stable API and is removed on @next.'
                        : 'exec(argv) menerima daftar argv dan selesai saat proses dimulai, mengembalikan handle (output(), logs(), waitForExit(), kill()). Tidak ada shell implisit. startProcess adalah API stable dan dihapus di @next.'}
                    </p>
                    <pre className="rounded bg-muted p-2 font-mono text-[10px] text-foreground">
                      {'const proc = await sandbox.exec(["npm", "test"])\nconst result = await proc.output({ encoding: "utf8" })\n// result.stdout, result.exitCode'}
                    </pre>
                  </div>
                )}

                <div className="border-t border-border pt-2 text-[10px] text-muted-foreground">
                  <strong className="text-foreground">{isEn ? 'Cutover Gate: ' : 'Pintu Cutover: '}</strong>
                  {isEn
                    ? 'Production migration requires explicit user confirmation before applying --containers-rollout=immediate.'
                    : 'Migrasi produksi mewajibkan persetujuan eksplisit user sebelum menerapkan --containers-rollout=immediate.'}
                </div>
              </div>
            </CardContent>
          </Card>
        </div>
      </div>
    </section>
  )
}
