/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SuperpowersRouteImport } from './routes/superpowers'
import { Route as MattpocockRouteImport } from './routes/mattpocock'
import { Route as JakubkrehelRouteImport } from './routes/jakubkrehel'
import { Route as EmilkowalskiRouteImport } from './routes/emilkowalski'
import { Route as DavidondrejRouteImport } from './routes/davidondrej'
import { Route as CollectionsRouteImport } from './routes/collections'
import { Route as BrooklynRouteImport } from './routes/brooklyn'
import { Route as IndexRouteImport } from './routes/index'
import { Route as EmilkowalskiIndexRouteImport } from './routes/emilkowalski.index'
import { Route as DavidondrejIndexRouteImport } from './routes/davidondrej.index'
import { Route as SkillsSkillNameRouteImport } from './routes/skills.$skillName'
import { Route as EmilkowalskiSkillsSkillNameRouteImport } from './routes/emilkowalski.skills.$skillName'
import { Route as DavidondrejSkillsSkillNameRouteImport } from './routes/davidondrej.skills.$skillName'

const SuperpowersRoute = SuperpowersRouteImport.update({
  id: '/superpowers',
  path: '/superpowers',
  getParentRoute: () => rootRouteImport,
} as any)
const MattpocockRoute = MattpocockRouteImport.update({
  id: '/mattpocock',
  path: '/mattpocock',
  getParentRoute: () => rootRouteImport,
} as any)
const JakubkrehelRoute = JakubkrehelRouteImport.update({
  id: '/jakubkrehel',
  path: '/jakubkrehel',
  getParentRoute: () => rootRouteImport,
} as any)
const EmilkowalskiRoute = EmilkowalskiRouteImport.update({
  id: '/emilkowalski',
  path: '/emilkowalski',
  getParentRoute: () => rootRouteImport,
} as any)
const DavidondrejRoute = DavidondrejRouteImport.update({
  id: '/davidondrej',
  path: '/davidondrej',
  getParentRoute: () => rootRouteImport,
} as any)
const CollectionsRoute = CollectionsRouteImport.update({
  id: '/collections',
  path: '/collections',
  getParentRoute: () => rootRouteImport,
} as any)
const BrooklynRoute = BrooklynRouteImport.update({
  id: '/brooklyn',
  path: '/brooklyn',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const EmilkowalskiIndexRoute = EmilkowalskiIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => EmilkowalskiRoute,
} as any)
const DavidondrejIndexRoute = DavidondrejIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DavidondrejRoute,
} as any)
const SkillsSkillNameRoute = SkillsSkillNameRouteImport.update({
  id: '/skills/$skillName',
  path: '/skills/$skillName',
  getParentRoute: () => rootRouteImport,
} as any)
const EmilkowalskiSkillsSkillNameRoute =
  EmilkowalskiSkillsSkillNameRouteImport.update({
    id: '/skills/$skillName',
    path: '/skills/$skillName',
    getParentRoute: () => EmilkowalskiRoute,
  } as any)
const DavidondrejSkillsSkillNameRoute =
  DavidondrejSkillsSkillNameRouteImport.update({
    id: '/skills/$skillName',
    path: '/skills/$skillName',
    getParentRoute: () => DavidondrejRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/brooklyn': typeof BrooklynRoute
  '/collections': typeof CollectionsRoute
  '/davidondrej': typeof DavidondrejRouteWithChildren
  '/emilkowalski': typeof EmilkowalskiRouteWithChildren
  '/jakubkrehel': typeof JakubkrehelRoute
  '/mattpocock': typeof MattpocockRoute
  '/superpowers': typeof SuperpowersRoute
  '/skills/$skillName': typeof SkillsSkillNameRoute
  '/davidondrej/': typeof DavidondrejIndexRoute
  '/emilkowalski/': typeof EmilkowalskiIndexRoute
  '/davidondrej/skills/$skillName': typeof DavidondrejSkillsSkillNameRoute
  '/emilkowalski/skills/$skillName': typeof EmilkowalskiSkillsSkillNameRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/brooklyn': typeof BrooklynRoute
  '/collections': typeof CollectionsRoute
  '/jakubkrehel': typeof JakubkrehelRoute
  '/mattpocock': typeof MattpocockRoute
  '/superpowers': typeof SuperpowersRoute
  '/skills/$skillName': typeof SkillsSkillNameRoute
  '/davidondrej': typeof DavidondrejIndexRoute
  '/emilkowalski': typeof EmilkowalskiIndexRoute
  '/davidondrej/skills/$skillName': typeof DavidondrejSkillsSkillNameRoute
  '/emilkowalski/skills/$skillName': typeof EmilkowalskiSkillsSkillNameRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/brooklyn': typeof BrooklynRoute
  '/collections': typeof CollectionsRoute
  '/davidondrej': typeof DavidondrejRouteWithChildren
  '/emilkowalski': typeof EmilkowalskiRouteWithChildren
  '/jakubkrehel': typeof JakubkrehelRoute
  '/mattpocock': typeof MattpocockRoute
  '/superpowers': typeof SuperpowersRoute
  '/skills/$skillName': typeof SkillsSkillNameRoute
  '/davidondrej/': typeof DavidondrejIndexRoute
  '/emilkowalski/': typeof EmilkowalskiIndexRoute
  '/davidondrej/skills/$skillName': typeof DavidondrejSkillsSkillNameRoute
  '/emilkowalski/skills/$skillName': typeof EmilkowalskiSkillsSkillNameRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/brooklyn'
    | '/collections'
    | '/davidondrej'
    | '/emilkowalski'
    | '/jakubkrehel'
    | '/mattpocock'
    | '/superpowers'
    | '/skills/$skillName'
    | '/davidondrej/'
    | '/emilkowalski/'
    | '/davidondrej/skills/$skillName'
    | '/emilkowalski/skills/$skillName'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/brooklyn'
    | '/collections'
    | '/jakubkrehel'
    | '/mattpocock'
    | '/superpowers'
    | '/skills/$skillName'
    | '/davidondrej'
    | '/emilkowalski'
    | '/davidondrej/skills/$skillName'
    | '/emilkowalski/skills/$skillName'
  id:
    | '__root__'
    | '/'
    | '/brooklyn'
    | '/collections'
    | '/davidondrej'
    | '/emilkowalski'
    | '/jakubkrehel'
    | '/mattpocock'
    | '/superpowers'
    | '/skills/$skillName'
    | '/davidondrej/'
    | '/emilkowalski/'
    | '/davidondrej/skills/$skillName'
    | '/emilkowalski/skills/$skillName'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BrooklynRoute: typeof BrooklynRoute
  CollectionsRoute: typeof CollectionsRoute
  DavidondrejRoute: typeof DavidondrejRouteWithChildren
  EmilkowalskiRoute: typeof EmilkowalskiRouteWithChildren
  JakubkrehelRoute: typeof JakubkrehelRoute
  MattpocockRoute: typeof MattpocockRoute
  SuperpowersRoute: typeof SuperpowersRoute
  SkillsSkillNameRoute: typeof SkillsSkillNameRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/superpowers': {
      id: '/superpowers'
      path: '/superpowers'
      fullPath: '/superpowers'
      preLoaderRoute: typeof SuperpowersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mattpocock': {
      id: '/mattpocock'
      path: '/mattpocock'
      fullPath: '/mattpocock'
      preLoaderRoute: typeof MattpocockRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jakubkrehel': {
      id: '/jakubkrehel'
      path: '/jakubkrehel'
      fullPath: '/jakubkrehel'
      preLoaderRoute: typeof JakubkrehelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/emilkowalski': {
      id: '/emilkowalski'
      path: '/emilkowalski'
      fullPath: '/emilkowalski'
      preLoaderRoute: typeof EmilkowalskiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/davidondrej': {
      id: '/davidondrej'
      path: '/davidondrej'
      fullPath: '/davidondrej'
      preLoaderRoute: typeof DavidondrejRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/collections': {
      id: '/collections'
      path: '/collections'
      fullPath: '/collections'
      preLoaderRoute: typeof CollectionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/brooklyn': {
      id: '/brooklyn'
      path: '/brooklyn'
      fullPath: '/brooklyn'
      preLoaderRoute: typeof BrooklynRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/emilkowalski/': {
      id: '/emilkowalski/'
      path: '/'
      fullPath: '/emilkowalski/'
      preLoaderRoute: typeof EmilkowalskiIndexRouteImport
      parentRoute: typeof EmilkowalskiRoute
    }
    '/davidondrej/': {
      id: '/davidondrej/'
      path: '/'
      fullPath: '/davidondrej/'
      preLoaderRoute: typeof DavidondrejIndexRouteImport
      parentRoute: typeof DavidondrejRoute
    }
    '/skills/$skillName': {
      id: '/skills/$skillName'
      path: '/skills/$skillName'
      fullPath: '/skills/$skillName'
      preLoaderRoute: typeof SkillsSkillNameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/emilkowalski/skills/$skillName': {
      id: '/emilkowalski/skills/$skillName'
      path: '/skills/$skillName'
      fullPath: '/emilkowalski/skills/$skillName'
      preLoaderRoute: typeof EmilkowalskiSkillsSkillNameRouteImport
      parentRoute: typeof EmilkowalskiRoute
    }
    '/davidondrej/skills/$skillName': {
      id: '/davidondrej/skills/$skillName'
      path: '/skills/$skillName'
      fullPath: '/davidondrej/skills/$skillName'
      preLoaderRoute: typeof DavidondrejSkillsSkillNameRouteImport
      parentRoute: typeof DavidondrejRoute
    }
  }
}

interface DavidondrejRouteChildren {
  DavidondrejIndexRoute: typeof DavidondrejIndexRoute
  DavidondrejSkillsSkillNameRoute: typeof DavidondrejSkillsSkillNameRoute
}

const DavidondrejRouteChildren: DavidondrejRouteChildren = {
  DavidondrejIndexRoute: DavidondrejIndexRoute,
  DavidondrejSkillsSkillNameRoute: DavidondrejSkillsSkillNameRoute,
}

const DavidondrejRouteWithChildren = DavidondrejRoute._addFileChildren(
  DavidondrejRouteChildren,
)

interface EmilkowalskiRouteChildren {
  EmilkowalskiIndexRoute: typeof EmilkowalskiIndexRoute
  EmilkowalskiSkillsSkillNameRoute: typeof EmilkowalskiSkillsSkillNameRoute
}

const EmilkowalskiRouteChildren: EmilkowalskiRouteChildren = {
  EmilkowalskiIndexRoute: EmilkowalskiIndexRoute,
  EmilkowalskiSkillsSkillNameRoute: EmilkowalskiSkillsSkillNameRoute,
}

const EmilkowalskiRouteWithChildren = EmilkowalskiRoute._addFileChildren(
  EmilkowalskiRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BrooklynRoute: BrooklynRoute,
  CollectionsRoute: CollectionsRoute,
  DavidondrejRoute: DavidondrejRouteWithChildren,
  EmilkowalskiRoute: EmilkowalskiRouteWithChildren,
  JakubkrehelRoute: JakubkrehelRoute,
  MattpocockRoute: MattpocockRoute,
  SuperpowersRoute: SuperpowersRoute,
  SkillsSkillNameRoute: SkillsSkillNameRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
