/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VercelRouteImport } from './routes/vercel'
import { Route as SuperpowersRouteImport } from './routes/superpowers'
import { Route as MattpocockRouteImport } from './routes/mattpocock'
import { Route as JakubkrehelRouteImport } from './routes/jakubkrehel'
import { Route as EmilkowalskiRouteImport } from './routes/emilkowalski'
import { Route as DavidondrejRouteImport } from './routes/davidondrej'
import { Route as CollectionsRouteImport } from './routes/collections'
import { Route as BrooklynRouteImport } from './routes/brooklyn'
import { Route as AnthropicRouteImport } from './routes/anthropic'
import { Route as IndexRouteImport } from './routes/index'
import { Route as VercelIndexRouteImport } from './routes/vercel.index'
import { Route as SuperpowersIndexRouteImport } from './routes/superpowers.index'
import { Route as JakubkrehelIndexRouteImport } from './routes/jakubkrehel.index'
import { Route as EmilkowalskiIndexRouteImport } from './routes/emilkowalski.index'
import { Route as DavidondrejIndexRouteImport } from './routes/davidondrej.index'
import { Route as BrooklynIndexRouteImport } from './routes/brooklyn.index'
import { Route as AnthropicIndexRouteImport } from './routes/anthropic.index'
import { Route as SkillsSkillNameRouteImport } from './routes/skills.$skillName'
import { Route as VercelSkillsSkillNameRouteImport } from './routes/vercel.skills.$skillName'
import { Route as SuperpowersSkillsSkillNameRouteImport } from './routes/superpowers.skills.$skillName'
import { Route as JakubkrehelSkillsSkillNameRouteImport } from './routes/jakubkrehel.skills.$skillName'
import { Route as EmilkowalskiSkillsSkillNameRouteImport } from './routes/emilkowalski.skills.$skillName'
import { Route as DavidondrejSkillsSkillNameRouteImport } from './routes/davidondrej.skills.$skillName'
import { Route as BrooklynSkillsSkillNameRouteImport } from './routes/brooklyn.skills.$skillName'
import { Route as AnthropicSkillsSkillNameRouteImport } from './routes/anthropic.skills.$skillName'

const VercelRoute = VercelRouteImport.update({
  id: '/vercel',
  path: '/vercel',
  getParentRoute: () => rootRouteImport,
} as any)
const SuperpowersRoute = SuperpowersRouteImport.update({
  id: '/superpowers',
  path: '/superpowers',
  getParentRoute: () => rootRouteImport,
} as any)
const MattpocockRoute = MattpocockRouteImport.update({
  id: '/mattpocock',
  path: '/mattpocock',
  getParentRoute: () => rootRouteImport,
} as any)
const JakubkrehelRoute = JakubkrehelRouteImport.update({
  id: '/jakubkrehel',
  path: '/jakubkrehel',
  getParentRoute: () => rootRouteImport,
} as any)
const EmilkowalskiRoute = EmilkowalskiRouteImport.update({
  id: '/emilkowalski',
  path: '/emilkowalski',
  getParentRoute: () => rootRouteImport,
} as any)
const DavidondrejRoute = DavidondrejRouteImport.update({
  id: '/davidondrej',
  path: '/davidondrej',
  getParentRoute: () => rootRouteImport,
} as any)
const CollectionsRoute = CollectionsRouteImport.update({
  id: '/collections',
  path: '/collections',
  getParentRoute: () => rootRouteImport,
} as any)
const BrooklynRoute = BrooklynRouteImport.update({
  id: '/brooklyn',
  path: '/brooklyn',
  getParentRoute: () => rootRouteImport,
} as any)
const AnthropicRoute = AnthropicRouteImport.update({
  id: '/anthropic',
  path: '/anthropic',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const VercelIndexRoute = VercelIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => VercelRoute,
} as any)
const SuperpowersIndexRoute = SuperpowersIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SuperpowersRoute,
} as any)
const JakubkrehelIndexRoute = JakubkrehelIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => JakubkrehelRoute,
} as any)
const EmilkowalskiIndexRoute = EmilkowalskiIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => EmilkowalskiRoute,
} as any)
const DavidondrejIndexRoute = DavidondrejIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DavidondrejRoute,
} as any)
const BrooklynIndexRoute = BrooklynIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => BrooklynRoute,
} as any)
const AnthropicIndexRoute = AnthropicIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AnthropicRoute,
} as any)
const SkillsSkillNameRoute = SkillsSkillNameRouteImport.update({
  id: '/skills/$skillName',
  path: '/skills/$skillName',
  getParentRoute: () => rootRouteImport,
} as any)
const VercelSkillsSkillNameRoute = VercelSkillsSkillNameRouteImport.update({
  id: '/skills/$skillName',
  path: '/skills/$skillName',
  getParentRoute: () => VercelRoute,
} as any)
const SuperpowersSkillsSkillNameRoute =
  SuperpowersSkillsSkillNameRouteImport.update({
    id: '/skills/$skillName',
    path: '/skills/$skillName',
    getParentRoute: () => SuperpowersRoute,
  } as any)
const JakubkrehelSkillsSkillNameRoute =
  JakubkrehelSkillsSkillNameRouteImport.update({
    id: '/skills/$skillName',
    path: '/skills/$skillName',
    getParentRoute: () => JakubkrehelRoute,
  } as any)
const EmilkowalskiSkillsSkillNameRoute =
  EmilkowalskiSkillsSkillNameRouteImport.update({
    id: '/skills/$skillName',
    path: '/skills/$skillName',
    getParentRoute: () => EmilkowalskiRoute,
  } as any)
const DavidondrejSkillsSkillNameRoute =
  DavidondrejSkillsSkillNameRouteImport.update({
    id: '/skills/$skillName',
    path: '/skills/$skillName',
    getParentRoute: () => DavidondrejRoute,
  } as any)
const BrooklynSkillsSkillNameRoute = BrooklynSkillsSkillNameRouteImport.update({
  id: '/skills/$skillName',
  path: '/skills/$skillName',
  getParentRoute: () => BrooklynRoute,
} as any)
const AnthropicSkillsSkillNameRoute =
  AnthropicSkillsSkillNameRouteImport.update({
    id: '/skills/$skillName',
    path: '/skills/$skillName',
    getParentRoute: () => AnthropicRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/anthropic': typeof AnthropicRouteWithChildren
  '/brooklyn': typeof BrooklynRouteWithChildren
  '/collections': typeof CollectionsRoute
  '/davidondrej': typeof DavidondrejRouteWithChildren
  '/emilkowalski': typeof EmilkowalskiRouteWithChildren
  '/jakubkrehel': typeof JakubkrehelRouteWithChildren
  '/mattpocock': typeof MattpocockRoute
  '/superpowers': typeof SuperpowersRouteWithChildren
  '/vercel': typeof VercelRouteWithChildren
  '/skills/$skillName': typeof SkillsSkillNameRoute
  '/anthropic/': typeof AnthropicIndexRoute
  '/brooklyn/': typeof BrooklynIndexRoute
  '/davidondrej/': typeof DavidondrejIndexRoute
  '/emilkowalski/': typeof EmilkowalskiIndexRoute
  '/jakubkrehel/': typeof JakubkrehelIndexRoute
  '/superpowers/': typeof SuperpowersIndexRoute
  '/vercel/': typeof VercelIndexRoute
  '/anthropic/skills/$skillName': typeof AnthropicSkillsSkillNameRoute
  '/brooklyn/skills/$skillName': typeof BrooklynSkillsSkillNameRoute
  '/davidondrej/skills/$skillName': typeof DavidondrejSkillsSkillNameRoute
  '/emilkowalski/skills/$skillName': typeof EmilkowalskiSkillsSkillNameRoute
  '/jakubkrehel/skills/$skillName': typeof JakubkrehelSkillsSkillNameRoute
  '/superpowers/skills/$skillName': typeof SuperpowersSkillsSkillNameRoute
  '/vercel/skills/$skillName': typeof VercelSkillsSkillNameRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/collections': typeof CollectionsRoute
  '/mattpocock': typeof MattpocockRoute
  '/skills/$skillName': typeof SkillsSkillNameRoute
  '/anthropic': typeof AnthropicIndexRoute
  '/brooklyn': typeof BrooklynIndexRoute
  '/davidondrej': typeof DavidondrejIndexRoute
  '/emilkowalski': typeof EmilkowalskiIndexRoute
  '/jakubkrehel': typeof JakubkrehelIndexRoute
  '/superpowers': typeof SuperpowersIndexRoute
  '/vercel': typeof VercelIndexRoute
  '/anthropic/skills/$skillName': typeof AnthropicSkillsSkillNameRoute
  '/brooklyn/skills/$skillName': typeof BrooklynSkillsSkillNameRoute
  '/davidondrej/skills/$skillName': typeof DavidondrejSkillsSkillNameRoute
  '/emilkowalski/skills/$skillName': typeof EmilkowalskiSkillsSkillNameRoute
  '/jakubkrehel/skills/$skillName': typeof JakubkrehelSkillsSkillNameRoute
  '/superpowers/skills/$skillName': typeof SuperpowersSkillsSkillNameRoute
  '/vercel/skills/$skillName': typeof VercelSkillsSkillNameRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/anthropic': typeof AnthropicRouteWithChildren
  '/brooklyn': typeof BrooklynRouteWithChildren
  '/collections': typeof CollectionsRoute
  '/davidondrej': typeof DavidondrejRouteWithChildren
  '/emilkowalski': typeof EmilkowalskiRouteWithChildren
  '/jakubkrehel': typeof JakubkrehelRouteWithChildren
  '/mattpocock': typeof MattpocockRoute
  '/superpowers': typeof SuperpowersRouteWithChildren
  '/vercel': typeof VercelRouteWithChildren
  '/skills/$skillName': typeof SkillsSkillNameRoute
  '/anthropic/': typeof AnthropicIndexRoute
  '/brooklyn/': typeof BrooklynIndexRoute
  '/davidondrej/': typeof DavidondrejIndexRoute
  '/emilkowalski/': typeof EmilkowalskiIndexRoute
  '/jakubkrehel/': typeof JakubkrehelIndexRoute
  '/superpowers/': typeof SuperpowersIndexRoute
  '/vercel/': typeof VercelIndexRoute
  '/anthropic/skills/$skillName': typeof AnthropicSkillsSkillNameRoute
  '/brooklyn/skills/$skillName': typeof BrooklynSkillsSkillNameRoute
  '/davidondrej/skills/$skillName': typeof DavidondrejSkillsSkillNameRoute
  '/emilkowalski/skills/$skillName': typeof EmilkowalskiSkillsSkillNameRoute
  '/jakubkrehel/skills/$skillName': typeof JakubkrehelSkillsSkillNameRoute
  '/superpowers/skills/$skillName': typeof SuperpowersSkillsSkillNameRoute
  '/vercel/skills/$skillName': typeof VercelSkillsSkillNameRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/anthropic'
    | '/brooklyn'
    | '/collections'
    | '/davidondrej'
    | '/emilkowalski'
    | '/jakubkrehel'
    | '/mattpocock'
    | '/superpowers'
    | '/vercel'
    | '/skills/$skillName'
    | '/anthropic/'
    | '/brooklyn/'
    | '/davidondrej/'
    | '/emilkowalski/'
    | '/jakubkrehel/'
    | '/superpowers/'
    | '/vercel/'
    | '/anthropic/skills/$skillName'
    | '/brooklyn/skills/$skillName'
    | '/davidondrej/skills/$skillName'
    | '/emilkowalski/skills/$skillName'
    | '/jakubkrehel/skills/$skillName'
    | '/superpowers/skills/$skillName'
    | '/vercel/skills/$skillName'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/collections'
    | '/mattpocock'
    | '/skills/$skillName'
    | '/anthropic'
    | '/brooklyn'
    | '/davidondrej'
    | '/emilkowalski'
    | '/jakubkrehel'
    | '/superpowers'
    | '/vercel'
    | '/anthropic/skills/$skillName'
    | '/brooklyn/skills/$skillName'
    | '/davidondrej/skills/$skillName'
    | '/emilkowalski/skills/$skillName'
    | '/jakubkrehel/skills/$skillName'
    | '/superpowers/skills/$skillName'
    | '/vercel/skills/$skillName'
  id:
    | '__root__'
    | '/'
    | '/anthropic'
    | '/brooklyn'
    | '/collections'
    | '/davidondrej'
    | '/emilkowalski'
    | '/jakubkrehel'
    | '/mattpocock'
    | '/superpowers'
    | '/vercel'
    | '/skills/$skillName'
    | '/anthropic/'
    | '/brooklyn/'
    | '/davidondrej/'
    | '/emilkowalski/'
    | '/jakubkrehel/'
    | '/superpowers/'
    | '/vercel/'
    | '/anthropic/skills/$skillName'
    | '/brooklyn/skills/$skillName'
    | '/davidondrej/skills/$skillName'
    | '/emilkowalski/skills/$skillName'
    | '/jakubkrehel/skills/$skillName'
    | '/superpowers/skills/$skillName'
    | '/vercel/skills/$skillName'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AnthropicRoute: typeof AnthropicRouteWithChildren
  BrooklynRoute: typeof BrooklynRouteWithChildren
  CollectionsRoute: typeof CollectionsRoute
  DavidondrejRoute: typeof DavidondrejRouteWithChildren
  EmilkowalskiRoute: typeof EmilkowalskiRouteWithChildren
  JakubkrehelRoute: typeof JakubkrehelRouteWithChildren
  MattpocockRoute: typeof MattpocockRoute
  SuperpowersRoute: typeof SuperpowersRouteWithChildren
  VercelRoute: typeof VercelRouteWithChildren
  SkillsSkillNameRoute: typeof SkillsSkillNameRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/vercel': {
      id: '/vercel'
      path: '/vercel'
      fullPath: '/vercel'
      preLoaderRoute: typeof VercelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/superpowers': {
      id: '/superpowers'
      path: '/superpowers'
      fullPath: '/superpowers'
      preLoaderRoute: typeof SuperpowersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mattpocock': {
      id: '/mattpocock'
      path: '/mattpocock'
      fullPath: '/mattpocock'
      preLoaderRoute: typeof MattpocockRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jakubkrehel': {
      id: '/jakubkrehel'
      path: '/jakubkrehel'
      fullPath: '/jakubkrehel'
      preLoaderRoute: typeof JakubkrehelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/emilkowalski': {
      id: '/emilkowalski'
      path: '/emilkowalski'
      fullPath: '/emilkowalski'
      preLoaderRoute: typeof EmilkowalskiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/davidondrej': {
      id: '/davidondrej'
      path: '/davidondrej'
      fullPath: '/davidondrej'
      preLoaderRoute: typeof DavidondrejRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/collections': {
      id: '/collections'
      path: '/collections'
      fullPath: '/collections'
      preLoaderRoute: typeof CollectionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/brooklyn': {
      id: '/brooklyn'
      path: '/brooklyn'
      fullPath: '/brooklyn'
      preLoaderRoute: typeof BrooklynRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/anthropic': {
      id: '/anthropic'
      path: '/anthropic'
      fullPath: '/anthropic'
      preLoaderRoute: typeof AnthropicRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vercel/': {
      id: '/vercel/'
      path: '/'
      fullPath: '/vercel/'
      preLoaderRoute: typeof VercelIndexRouteImport
      parentRoute: typeof VercelRoute
    }
    '/superpowers/': {
      id: '/superpowers/'
      path: '/'
      fullPath: '/superpowers/'
      preLoaderRoute: typeof SuperpowersIndexRouteImport
      parentRoute: typeof SuperpowersRoute
    }
    '/jakubkrehel/': {
      id: '/jakubkrehel/'
      path: '/'
      fullPath: '/jakubkrehel/'
      preLoaderRoute: typeof JakubkrehelIndexRouteImport
      parentRoute: typeof JakubkrehelRoute
    }
    '/emilkowalski/': {
      id: '/emilkowalski/'
      path: '/'
      fullPath: '/emilkowalski/'
      preLoaderRoute: typeof EmilkowalskiIndexRouteImport
      parentRoute: typeof EmilkowalskiRoute
    }
    '/davidondrej/': {
      id: '/davidondrej/'
      path: '/'
      fullPath: '/davidondrej/'
      preLoaderRoute: typeof DavidondrejIndexRouteImport
      parentRoute: typeof DavidondrejRoute
    }
    '/brooklyn/': {
      id: '/brooklyn/'
      path: '/'
      fullPath: '/brooklyn/'
      preLoaderRoute: typeof BrooklynIndexRouteImport
      parentRoute: typeof BrooklynRoute
    }
    '/anthropic/': {
      id: '/anthropic/'
      path: '/'
      fullPath: '/anthropic/'
      preLoaderRoute: typeof AnthropicIndexRouteImport
      parentRoute: typeof AnthropicRoute
    }
    '/skills/$skillName': {
      id: '/skills/$skillName'
      path: '/skills/$skillName'
      fullPath: '/skills/$skillName'
      preLoaderRoute: typeof SkillsSkillNameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vercel/skills/$skillName': {
      id: '/vercel/skills/$skillName'
      path: '/skills/$skillName'
      fullPath: '/vercel/skills/$skillName'
      preLoaderRoute: typeof VercelSkillsSkillNameRouteImport
      parentRoute: typeof VercelRoute
    }
    '/superpowers/skills/$skillName': {
      id: '/superpowers/skills/$skillName'
      path: '/skills/$skillName'
      fullPath: '/superpowers/skills/$skillName'
      preLoaderRoute: typeof SuperpowersSkillsSkillNameRouteImport
      parentRoute: typeof SuperpowersRoute
    }
    '/jakubkrehel/skills/$skillName': {
      id: '/jakubkrehel/skills/$skillName'
      path: '/skills/$skillName'
      fullPath: '/jakubkrehel/skills/$skillName'
      preLoaderRoute: typeof JakubkrehelSkillsSkillNameRouteImport
      parentRoute: typeof JakubkrehelRoute
    }
    '/emilkowalski/skills/$skillName': {
      id: '/emilkowalski/skills/$skillName'
      path: '/skills/$skillName'
      fullPath: '/emilkowalski/skills/$skillName'
      preLoaderRoute: typeof EmilkowalskiSkillsSkillNameRouteImport
      parentRoute: typeof EmilkowalskiRoute
    }
    '/davidondrej/skills/$skillName': {
      id: '/davidondrej/skills/$skillName'
      path: '/skills/$skillName'
      fullPath: '/davidondrej/skills/$skillName'
      preLoaderRoute: typeof DavidondrejSkillsSkillNameRouteImport
      parentRoute: typeof DavidondrejRoute
    }
    '/brooklyn/skills/$skillName': {
      id: '/brooklyn/skills/$skillName'
      path: '/skills/$skillName'
      fullPath: '/brooklyn/skills/$skillName'
      preLoaderRoute: typeof BrooklynSkillsSkillNameRouteImport
      parentRoute: typeof BrooklynRoute
    }
    '/anthropic/skills/$skillName': {
      id: '/anthropic/skills/$skillName'
      path: '/skills/$skillName'
      fullPath: '/anthropic/skills/$skillName'
      preLoaderRoute: typeof AnthropicSkillsSkillNameRouteImport
      parentRoute: typeof AnthropicRoute
    }
  }
}

interface AnthropicRouteChildren {
  AnthropicIndexRoute: typeof AnthropicIndexRoute
  AnthropicSkillsSkillNameRoute: typeof AnthropicSkillsSkillNameRoute
}

const AnthropicRouteChildren: AnthropicRouteChildren = {
  AnthropicIndexRoute: AnthropicIndexRoute,
  AnthropicSkillsSkillNameRoute: AnthropicSkillsSkillNameRoute,
}

const AnthropicRouteWithChildren = AnthropicRoute._addFileChildren(
  AnthropicRouteChildren,
)

interface BrooklynRouteChildren {
  BrooklynIndexRoute: typeof BrooklynIndexRoute
  BrooklynSkillsSkillNameRoute: typeof BrooklynSkillsSkillNameRoute
}

const BrooklynRouteChildren: BrooklynRouteChildren = {
  BrooklynIndexRoute: BrooklynIndexRoute,
  BrooklynSkillsSkillNameRoute: BrooklynSkillsSkillNameRoute,
}

const BrooklynRouteWithChildren = BrooklynRoute._addFileChildren(
  BrooklynRouteChildren,
)

interface DavidondrejRouteChildren {
  DavidondrejIndexRoute: typeof DavidondrejIndexRoute
  DavidondrejSkillsSkillNameRoute: typeof DavidondrejSkillsSkillNameRoute
}

const DavidondrejRouteChildren: DavidondrejRouteChildren = {
  DavidondrejIndexRoute: DavidondrejIndexRoute,
  DavidondrejSkillsSkillNameRoute: DavidondrejSkillsSkillNameRoute,
}

const DavidondrejRouteWithChildren = DavidondrejRoute._addFileChildren(
  DavidondrejRouteChildren,
)

interface EmilkowalskiRouteChildren {
  EmilkowalskiIndexRoute: typeof EmilkowalskiIndexRoute
  EmilkowalskiSkillsSkillNameRoute: typeof EmilkowalskiSkillsSkillNameRoute
}

const EmilkowalskiRouteChildren: EmilkowalskiRouteChildren = {
  EmilkowalskiIndexRoute: EmilkowalskiIndexRoute,
  EmilkowalskiSkillsSkillNameRoute: EmilkowalskiSkillsSkillNameRoute,
}

const EmilkowalskiRouteWithChildren = EmilkowalskiRoute._addFileChildren(
  EmilkowalskiRouteChildren,
)

interface JakubkrehelRouteChildren {
  JakubkrehelIndexRoute: typeof JakubkrehelIndexRoute
  JakubkrehelSkillsSkillNameRoute: typeof JakubkrehelSkillsSkillNameRoute
}

const JakubkrehelRouteChildren: JakubkrehelRouteChildren = {
  JakubkrehelIndexRoute: JakubkrehelIndexRoute,
  JakubkrehelSkillsSkillNameRoute: JakubkrehelSkillsSkillNameRoute,
}

const JakubkrehelRouteWithChildren = JakubkrehelRoute._addFileChildren(
  JakubkrehelRouteChildren,
)

interface SuperpowersRouteChildren {
  SuperpowersIndexRoute: typeof SuperpowersIndexRoute
  SuperpowersSkillsSkillNameRoute: typeof SuperpowersSkillsSkillNameRoute
}

const SuperpowersRouteChildren: SuperpowersRouteChildren = {
  SuperpowersIndexRoute: SuperpowersIndexRoute,
  SuperpowersSkillsSkillNameRoute: SuperpowersSkillsSkillNameRoute,
}

const SuperpowersRouteWithChildren = SuperpowersRoute._addFileChildren(
  SuperpowersRouteChildren,
)

interface VercelRouteChildren {
  VercelIndexRoute: typeof VercelIndexRoute
  VercelSkillsSkillNameRoute: typeof VercelSkillsSkillNameRoute
}

const VercelRouteChildren: VercelRouteChildren = {
  VercelIndexRoute: VercelIndexRoute,
  VercelSkillsSkillNameRoute: VercelSkillsSkillNameRoute,
}

const VercelRouteWithChildren =
  VercelRoute._addFileChildren(VercelRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AnthropicRoute: AnthropicRouteWithChildren,
  BrooklynRoute: BrooklynRouteWithChildren,
  CollectionsRoute: CollectionsRoute,
  DavidondrejRoute: DavidondrejRouteWithChildren,
  EmilkowalskiRoute: EmilkowalskiRouteWithChildren,
  JakubkrehelRoute: JakubkrehelRouteWithChildren,
  MattpocockRoute: MattpocockRoute,
  SuperpowersRoute: SuperpowersRouteWithChildren,
  VercelRoute: VercelRouteWithChildren,
  SkillsSkillNameRoute: SkillsSkillNameRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
