import type { BilingualString, BilingualList } from '@/types/skill'

export const TANSTACK_SOURCE_REPO = 'github.com/tanstack-skills/tanstack-skills'
export const TANSTACK_SOURCE_SHA = 'main'
export const SOURCE_REPO = TANSTACK_SOURCE_REPO
export const SOURCE_SHA = TANSTACK_SOURCE_SHA

export type RichSkill = {
  name: string
  category: string
  invocation: 'user' | 'model'
  description: BilingualString
  detailedDescription: BilingualString
  useWhen: BilingualList
  avoidWhen: BilingualList
  howItWorks: BilingualList
  coreRules: BilingualList
  tips: BilingualList
  pairsWellWith: string[]
  sourcePath: string
  spotlight?: {
    title: BilingualString
    body: BilingualString
  }
}

export const tanstackSkills: RichSkill[] = [
  {
    name: 'tanstack-router',
    category: 'routing-framework',
    invocation: 'model',
    description: {
      id: 'Routing 100% type-safe untuk React & Solid: file-based routing, pengelolaan search params kelas satu, data loading terintegrasi, dan code splitting otomatis.',
      en: '100% type-safe routing for React & Solid: file-based routing, first-class search params management, integrated data loading, and automatic code splitting.',
    },
    detailedDescription: {
      id: 'Skill resmi untuk TanStack Router (@tanstack/react-router). Membangun rute aplikasi dengan inferensi tipe end-to-end dari URL path, search params, hingga loader data. Mendukung struktur file routes (`routeTree.gen.ts`), validasi schema search params dengan Zod/Valibot, pemuatan data rute via loader dengan caching SWR bawaan, hooks `beforeLoad` untuk auth guard & redirects, preloading link cerdas, serta penanganan error boundary dan notFound(). Menjadi pondasi routing inti untuk framework TanStack Start.',
      en: 'Official skill for TanStack Router (@tanstack/react-router). Constructs application routes with end-to-end type safety across path segments, query search parameters, and route loader payloads. Supports file-based route generation (`routeTree.gen.ts`), schema-validated search params with Zod/Valibot, declarative data loading with integrated SWR caching, `beforeLoad` hooks for authentication guards & redirects, intelligent link preloading, and graceful error boundaries & notFound() states. Serves as the foundational routing engine for TanStack Start.',
    },
    useWhen: {
      id: [
        'Membangun Single Page Application (SPA) atau Full-stack React dengan navigasi type-safe.',
        'Mengelola search parameter URL yang kompleks dan terstruktur (filter, pagination, tab).',
        'Mengimplementasikan route guards dan otorisasi sebelum halaman dimuat (`beforeLoad`).',
        'Mengoptimalkan pemisahan bundle kode per-rute dengan auto code-splitting.',
      ],
      en: [
        'Building type-safe client SPAs or full-stack React applications.',
        'Managing complex, typed URL query parameters (filters, pagination, active tabs).',
        'Implementing authentication guards and redirects prior to rendering (`beforeLoad`).',
        'Optimizing per-route bundle payloads with automatic code-splitting.',
      ],
    },
    avoidWhen: {
      id: [
        'Aplikasi Next.js yang menggunakan bawaan App Router (`next/navigation`).',
        'Situs statis sederhana tanpa kebutuhan routing dinamis atau query state.',
      ],
      en: [
        'Next.js applications locked into native App Router primitives (`next/navigation`).',
        'Minimal static brochure websites without dynamic routing or query state requirements.',
      ],
    },
    howItWorks: {
      id: [
        'Mendefinisikan rute via `createFileRoute` pada folder `src/routes/`.',
        'Plugin Vite/Router secara otomatis menghasilkan `src/routeTree.gen.ts` secara deterministik.',
        'Memvalidasi search params menggunakan schema Zod di dalam properti `validateSearch`.',
        'Memuat data awal via fungsi `loader` yang langsung tersedia secara type-safe di komponen via `Route.useLoaderData()`.',
      ],
      en: [
        'Defines routes via `createFileRoute` across the `src/routes/` directory.',
        'Vite/Router compiler plugin automatically emits `src/routeTree.gen.ts`.',
        'Validates search parameters using Zod schemas declared in `validateSearch`.',
        'Fetches route data via `loader` functions accessible in components with full inference via `Route.useLoaderData()`.',
      ],
    },
    coreRules: {
      id: [
        'Jangan pernah mengedit `src/routeTree.gen.ts` secara manual; file ini dihasilkan oleh compiler router.',
        'Selalu gunakan `validateSearch` untuk seluruh search parameters agar state URL terjamin type-safe.',
        'Gunakan `beforeLoad` untuk pengecekan autentikasi agar rute terproteksi sebelum loader data dieksekusi.',
      ],
      en: [
        'Never hand-edit `src/routeTree.gen.ts`; it is deterministically generated by the router compiler.',
        'Always validate search parameters with `validateSearch` to enforce type safety over URL query states.',
        'Use `beforeLoad` for authentication checks so unauthorized requests are redirected before loaders fire.',
      ],
    },
    tips: {
      id: [
        'Gunakan opsi `preload: "intent"` pada komponen `<Link>` untuk memuat data saat kursor mouse hover di atas tautan.',
        'Gunakan tanda petik dolar `$param` untuk rute dinamis dan `_layout` untuk rute pengelompokan tanpa path segment.',
      ],
      en: [
        'Enable `preload: "intent"` on `<Link>` components to trigger background data prefetching on hover.',
        'Use `$param` notation for dynamic segments and `_layout` prefixes for pathless grouping layouts.',
      ],
    },
    pairsWellWith: ['tanstack-query', 'tanstack-start', 'tanstack-form'],
    spotlight: {
      title: {
        id: 'Search Params Sebagai State Manager Utama',
        en: 'Search Params as First-Class State Management',
      },
      body: {
        id: 'Banyak aplikasi web menyimpan status filter, modal, dan pagination di state React lokal (`useState`), sehingga URL tidak bisa dibagikan (unshareable) dan hilang saat refresh. TanStack Router memperlakukan search params sebagai state manager kelas satu: parameter di-parse secara terstruktur menjadi objek JSON type-safe melalui schema Zod, memungkinkan state sinkron sempurna antara URL browser dan komponen UI.',
        en: 'Many web applications mistakenly store filters, modals, and pagination inside local React `useState`, resulting in unshareable links that reset on refresh. TanStack Router treats search params as first-class state primitives: parameters are parsed into typed JSON objects via Zod validation, enabling seamless bidirectional synchronization between the browser URL and UI state.',
      },
    },
    sourcePath: 'plugins/tanstack-router/skills/tanstack-router/SKILL.md',
  },
  {
    name: 'tanstack-query',
    category: 'state-fetching',
    invocation: 'model',
    description: {
      id: 'Pengelolaan asynchronous server state standar industri: caching otomatis, background refetching, SWR, pagination, infinite scroll, dan optimistic updates.',
      en: 'Industry-standard asynchronous server state management: automatic caching, background refetching, SWR, pagination, infinite scroll, and optimistic updates.',
    },
    detailedDescription: {
      id: 'Skill referensi utama untuk TanStack Query (@tanstack/react-query, sebelumnya React Query). Mengelola siklus hidup data server secara deklaratif: deduplikasi request, caching cerdas, sinkronisasi latar belakang saat window focus, garbage collection data usang, pagination bertahap, infinite queries, serta mutasi dengan pembaruan UI optimis (optimistic updates) dan rollback otomatis saat terjadi kegagalan jaringan.',
      en: 'Flagship reference skill for TanStack Query (@tanstack/react-query, formerly React Query). Declaratively manages server state lifecycles: request deduplication, intelligent caching, background refetching on window focus, stale data garbage collection, stepped pagination, infinite queries, and mutations with optimistic UI reconciliation and automatic network failure rollbacks.',
    },
    useWhen: {
      id: [
        'Mengambil, mencache, atau memperbarui data dari REST API, GraphQL, atau RPC di aplikasi web/mobile.',
        'Mengimplementasikan polling latar belakang atau sinkronisasi data realtime.',
        'Membangun infinite list dengan pagination kursor atau tombol load more.',
        'Menerapkan mutasi dengan feedback visual instan (optimistic updates).',
      ],
      en: [
        'Fetching, caching, or mutating data from REST, GraphQL, or RPC endpoints.',
        'Implementing background polling or real-time server synchronization.',
        'Building infinite scrolling lists with cursor pagination or load-more triggers.',
        'Executing mutations with immediate visual feedback (optimistic updates).',
      ],
    },
    avoidWhen: {
      id: [
        'State sinkron murni sisi klien seperti tema gelap/terang atau toggle menu (gunakan tanstack-store atau React state).',
      ],
      en: [
        'Purely synchronous client-only state like dark mode toggles or modal state (use tanstack-store or React state).',
      ],
    },
    howItWorks: {
      id: [
        'Membuat query dengan array `queryKey` deterministik yang merefleksikan dependensi kueri.',
        'Menentukan fungsi `queryFn` asynchronous untuk mengambil data.',
        'Mengonfigurasi `staleTime` untuk menentukan seberapa lama data dianggap segar sebelum refetch latar belakang dilakukan.',
        'Menggunakan `useMutation` dengan callback `onMutate` untuk menulis data sementara ke cache sebelum response server tiba.',
      ],
      en: [
        'Declares queries with deterministic array `queryKey`s representing all query dependencies.',
        'Defines asynchronous `queryFn` handlers to fetch external data.',
        'Configures `staleTime` to govern data freshness intervals before triggering background revalidation.',
        'Employs `useMutation` with `onMutate` hooks to write tentative updates to cache prior to server acknowledgements.',
      ],
    },
    coreRules: {
      id: [
        'Selalu sertakan seluruh variabel yang digunakan di dalam `queryFn` ke dalam array `queryKey`.',
        'Konfigurasikan `staleTime` secara sengaja; nilai default `0` berarti data dianggap basi seketika.',
        'Gunakan `queryClient.invalidateQueries` alih-alih me-refetch secara manual setelah mutasi berhasil.',
      ],
      en: [
        'Always include all variables consumed inside `queryFn` within the `queryKey` array.',
        'Set intentional `staleTime` values; the default `0` marks data stale immediately upon mount.',
        'Use `queryClient.invalidateQueries` instead of manually triggering refetches after mutations.',
      ],
    },
    tips: {
      id: [
        'Gunakan factory object kueri (query options factory) untuk menyatukan queryKey dan queryFn agar reusable di seluruh app.',
        'Gunakan Devtools (@tanstack/react-query-devtools) untuk memantau status cache secara visual saat development.',
      ],
      en: [
        'Adopt query options factory patterns to centralize queryKeys and queryFns for shared reuse.',
        'Install `@tanstack/react-query-devtools` to visually inspect cache lifecycles during development.',
      ],
    },
    pairsWellWith: ['tanstack-router', 'tanstack-table', 'tanstack-db'],
    spotlight: {
      title: {
        id: 'Optimistic Updates Tanpa Data Berkedip',
        en: 'Flicker-Free Optimistic Updates',
      },
      body: {
        id: 'Pola mutasi optimis yang benar di TanStack Query membutuhkan 3 langkah ketat di `useMutation`: 1) Batalkan kueri yang sedang berlangsung via `cancelQueries` agar tidak menimpa data sementara; 2) Simpan snapshot data sebelumnya via context; 3) Set data optimis via `setQueryData`. Jika mutasi gagal di blok `onError`, pulihkan cache dari snapshot context. Jika berhasil di `onSettled`, lakukan invalidasi agar data tersinkron sempurna dengan server.',
        en: 'Proper optimistic updates in TanStack Query require 3 disciplined phases inside `useMutation`: 1) Cancel in-flight fetches via `cancelQueries` to prevent race conditions; 2) Snapshot the previous cache state into context; 3) Inject the optimistic payload with `setQueryData`. If the mutation fails, rollback using the snapshot in `onError`. In `onSettled`, invalidate the query to re-sync authoritative server state.',
      },
    },
    sourcePath: 'plugins/tanstack-query/skills/tanstack-query/SKILL.md',
  },
  {
    name: 'tanstack-table',
    category: 'headless-ui',
    invocation: 'model',
    description: {
      id: 'Headless UI untuk membangun tabel dan datagrid berkekuatan tinggi: pengurutan, penyaringan fuzzy, pagination, pinning kolom, grouping, dan row selection.',
      en: 'Headless UI for high-performance datagrids: sorting, fuzzy filtering, pagination, column pinning, grouping, and row selection.',
    },
    detailedDescription: {
      id: 'Skill resmi untuk TanStack Table (@tanstack/react-table, sebelumnya React Table). Merupakan library headless 100%: menyediakan seluruh logika komputasi data tabel (sorting multi-kolom, filter teks dan facet, pagination klien/server, grouping, expanding baris, column reordering, resizing, dan visibility) tanpa memaksakan satu pun elemen HTML atau class CSS. Memberikan kebebasan total bagi developer untuk merender tabel menggunakan Tailwind, shadcn/ui, atau sistem desain kustom.',
      en: 'Official skill for TanStack Table (@tanstack/react-table, formerly React Table). Operates as a pure 100% headless library: encapsulates all datagrid state logic (multi-column sorting, facet & text filters, client/server pagination, row grouping, sub-row expansion, column pinning, resizing, and visibility) without dictating any HTML tags or CSS styles. Grants engineers complete aesthetic freedom to render markup via Tailwind CSS, shadcn/ui, or proprietary design tokens.',
    },
    useWhen: {
      id: [
        'Membangun tabel data yang membutuhkan sorting, search filter, atau pagination.',
        'Mengimplementasikan fitur datagrid tingkat lanjut: column reordering, sticky header/column, atau row expansion.',
        'Mendesain tabel kustom dengan komponen UI seperti shadcn/ui atau Tailwind CSS.',
      ],
      en: [
        'Building datagrids requiring multi-column sorting, search filters, or pagination.',
        'Implementing advanced table capabilities: column pinning, sticky headers, or nested row expansion.',
        'Constructing custom tables with headless design systems like shadcn/ui or Tailwind CSS.',
      ],
    },
    avoidWhen: {
      id: [
        'Tabel data statis kecil (< 5 baris) yang tidak membutuhkan interaktivitas sorting atau filtering.',
      ],
      en: [
        'Simple static tables (< 5 rows) that require zero interactive filtering or sorting.',
      ],
    },
    howItWorks: {
      id: [
        'Mendefinisikan kolom secara type-safe menggunakan helper `createColumnHelper`.',
        'Memanggil hook `useReactTable` dengan memasukkan dataset dan konfigurasi fitur yang diinginkan.',
        'Melakukan iterasi pada `table.getHeaderGroups()` untuk merender elemen `<th>` dan `table.getRowModel().rows` untuk `<tr>`.',
        'Menerapkan fungsi fleksibel untuk sorting (`getSortedRowModel`), filtering (`getFilteredRowModel`), dan pagination (`getPaginationRowModel`).',
      ],
      en: [
        'Declares type-safe columns using `createColumnHelper`.',
        'Invokes `useReactTable` passing the dataset and feature configurations.',
        'Maps over `table.getHeaderGroups()` to output `<th>` elements and `table.getRowModel().rows` for `<tr>` rows.',
        'Chains pipeline processors for sorting (`getSortedRowModel`), filtering (`getFilteredRowModel`), and pagination (`getPaginationRowModel`).',
      ],
    },
    coreRules: {
      id: [
        'Pastikan data array di-memoize atau distabilkan agar `useReactTable` tidak me-recompute seluruh baris pada setiap render.',
        'Gunakan `createColumnHelper<T>()` untuk menjaga inferensi TypeScript yang akurat pada setiap accessor kolom.',
        'Pisahkan pagination server-side (`manualPagination: true`) untuk dataset besar daripada memuat seluruh data ke klien.',
      ],
      en: [
        'Memoize or stabilize data arrays so `useReactTable` avoids recalculating rows on extraneous re-renders.',
        'Use `createColumnHelper<T>()` to maintain compile-time type safety across column accessor keys.',
        'Enable server-side pagination (`manualPagination: true`) on large enterprise datasets.',
      ],
    },
    tips: {
      id: [
        'Pasangkan dengan `@tanstack/match-sorter-utils` untuk mendapatkan fuzzy search filtering berkecepatan tinggi.',
        'Gabungkan dengan `@tanstack/react-virtual` jika tabel harus merender lebih dari 1.000 baris secara simultan.',
      ],
      en: [
        'Pair with `@tanstack/match-sorter-utils` for instant fuzzy search filtering.',
        'Combine with `@tanstack/react-virtual` when rendering tables exceeding 1,000 concurrent rows.',
      ],
    },
    pairsWellWith: ['tanstack-virtual', 'tanstack-query', 'tanstack-form'],
    spotlight: {
      title: {
        id: 'Arsitektur Headless: Logika Murni Tanpa Polusi Markup',
        en: 'Headless Architecture: Pure Logic Without Markup Pollution',
      },
      body: {
        id: 'Keunggulan mutlak TanStack Table terletak pada filosofi headless: library hanya mengembalikan getter fungsi (`cell.getContext()`, `header.getToggleSortingHandler()`). Developer memiliki kendali penuh atas markup HTML (apakah menggunakan tag `<table>`, CSS Grid, atau `<div>` virtualized), sehingga integrasi ke sistem desain apa pun (shadcn, Tailwind, Chakra) bersih tanpa ada stylesheet yang saling bentrok.',
        en: 'The definitive advantage of TanStack Table is its pure headless philosophy: the library exposes handler getters (`cell.getContext()`, `header.getToggleSortingHandler()`) without emitting a single DOM node. Engineers retain total freedom over markup (native `<table>`, CSS Grid, or virtualized `<div>`s), ensuring zero CSS conflicts with design libraries like shadcn or Tailwind.',
      },
    },
    sourcePath: 'plugins/tanstack-table/skills/tanstack-table/SKILL.md',
  },
  {
    name: 'tanstack-form',
    category: 'form-management',
    invocation: 'model',
    description: {
      id: 'Manajemen form headless dan type-safe: validasi sinkron/asinkron tingkat field & form, array fields, fine-grained reactivity, dan adapter Zod/Valibot.',
      en: 'Headless, type-safe form management: field & form-level sync/async validation, array fields, fine-grained reactivity, and Zod/Valibot adapters.',
    },
    detailedDescription: {
      id: 'Skill resmi untuk TanStack Form (@tanstack/react-form). Mengelola status formulir kompleks dengan reaktivitas presisi tinggi (hanya komponen field yang berubah yang me-re-render, bukan seluruh formulir). Mendukung validasi ganda (sync on-change, async on-blur), integrasi skema validasi deklaratif via adapter (@tanstack/zod-form-adapter, @tanstack/valibot-form-adapter), manipulasi dynamic array fields, form submission terkelola, dan integrasi mulus dengan server actions atau API endpoints.',
      en: 'Official skill for TanStack Form (@tanstack/react-form). Governs complex form state with surgical fine-grained reactivity (only touched field nodes re-render rather than the whole form tree). Supports dual validation pipelines (synchronous on-change, asynchronous on-blur), schema integration via adapters (@tanstack/zod-form-adapter, @tanstack/valibot-form-adapter), dynamic array fields, controlled submissions, and clean integration with Server Functions and APIs.',
    },
    useWhen: {
      id: [
        'Membangun formulir dengan kebutuhan validasi ketat dan pesan error dinamis.',
        'Mengelola formulir dengan field dinamis (tambah/kurang baris, input bersarang).',
        'Mengoptimalkan performa formulir panjang agar pengetikan input tidak memicu re-render global.',
      ],
      en: [
        'Building forms requiring rigorous validation logic and dynamic inline error feedback.',
        'Managing dynamic form schemas (add/remove sub-items, nested inputs).',
        'Eliminating input lag on large forms by isolating field re-renders.',
      ],
    },
    avoidWhen: {
      id: [
        'Input pencarian sederhana satu field tanpa kebutuhan validasi skema.',
      ],
      en: [
        'Simple single-input search bars without validation rules.',
      ],
    },
    howItWorks: {
      id: [
        'Membuat instance form via `useForm` dengan nilai default dan validator skema.',
        'Membungkus elemen input ke dalam komponen `<form.Field>` yang menyuntikkan `field.state` dan `field.handleChange`.',
        'Menangani event `form.handleSubmit` untuk memvalidasi seluruh field sebelum callback submit dieksekusi.',
      ],
      en: [
        'Creates form instances via `useForm` with default values and schema validators.',
        'Wraps input elements in `<form.Field>` components injecting `field.state` and `field.handleChange`.',
        'Intercepts submissions via `form.handleSubmit` to validate all nodes before dispatching actions.',
      ],
    },
    coreRules: {
      id: [
        'Gunakan validator adapter (misal Zod) untuk validasi skema menyeluruh agar tipe TypeScript sinkron.',
        'Gunakan `field.Subscribe` untuk komponen yang hanya perlu mendengarkan sebagian kecil status field.',
      ],
      en: [
        'Employ validation adapters (e.g. Zod) to guarantee compile-time TypeScript type synchronization.',
        'Use `field.Subscribe` for components that only need to observe narrow field slices.',
      ],
    },
    tips: {
      id: [
        'Gunakan opsi `asyncDebounceMs` pada field dengan validasi server (misal cek ketersediaan username) untuk mencegah spam kueri.',
      ],
      en: [
        'Configure `asyncDebounceMs` on async validation fields (e.g. username availability checks) to debounce network traffic.',
      ],
    },
    pairsWellWith: ['tanstack-router', 'tanstack-query', 'tanstack-table'],
    spotlight: {
      title: {
        id: 'Fine-Grained Reactivity: Mengetik Tanpa Lag',
        en: 'Fine-Grained Reactivity: Lag-Free Input Rendering',
      },
      body: {
        id: 'Library form klasik sering kali menyimpan seluruh state di level root form, menyebabkan setiap ketikan satu karakter me-re-render puluhan input lainnya di layar. TanStack Form menggunakan reactive store terdistribusi: setiap input terbungkus di listener tersendiri, sehingga ketikan di Field A hanya mengeksekusi re-render pada Field A saja. Hasilnya: nol lag pada form multi-halaman berukuran besar.',
        en: 'Legacy form packages store the entire form payload in root state, causing every single keystroke to re-render dozens of surrounding DOM inputs. TanStack Form leverages fine-grained reactive subscriptions: each input is isolated in its own subscription boundary, ensuring typing in Field A only re-renders Field A. The result is zero input lag on enterprise-scale forms.',
      },
    },
    sourcePath: 'plugins/tanstack-form/skills/tanstack-form/SKILL.md',
  },
  {
    name: 'tanstack-start',
    category: 'fullstack-framework',
    invocation: 'model',
    description: {
      id: 'Full-stack React framework bertenaga TanStack Router, Vite, dan Nitro: SSR streaming, server functions (RPC), middleware, dan deploy ke host mana saja.',
      en: 'Full-stack React framework powered by TanStack Router, Vite, and Nitro: SSR streaming, server functions (RPC), middleware, and deploy to any hosting target.',
    },
    detailedDescription: {
      id: 'Skill arsitektur untuk framework full-stack TanStack Start (@tanstack/react-start). Menggabungkan kekuatan TanStack Router, kompilator Vite, dan server engine Nitro (via Vinxi). Menyediakan server-side rendering (SSR) dengan streaming HTML, pemanggilan server functions type-safe (`createServerFn`), middleware keamanan terpadu, penanganan API routes, serta kemampuan deployment lintas platform (Cloudflare Workers, Vercel, Node.js, AWS, Deno) via Nitro presets.',
      en: 'Architectural skill for the TanStack Start full-stack React framework (@tanstack/react-start). Unifies TanStack Router, Vite compilation, and the Nitro server runtime (via Vinxi). Delivers server-side rendering (SSR) with streaming HTML, type-safe Server Functions (`createServerFn`), unified middleware security pipelines, API route handlers, and multi-cloud deployment portability (Cloudflare Workers, Vercel, Node.js, AWS, Deno) via Nitro presets.',
    },
    useWhen: {
      id: [
        'Membangun aplikasi web full-stack React modern dengan kebutuhan SSR dan SEO optimal.',
        'Mengeksekusi logika backend (kueri database, autentikasi) via Server Functions tanpa membuat endpoint REST terpisah.',
        'Mendeploy aplikasi full-stack ke platform edge seperti Cloudflare Workers atau serverless Vercel.',
      ],
      en: [
        'Building modern full-stack React web applications with SSR and SEO requirements.',
        'Executing backend logic (database queries, auth) via type-safe Server Functions without manual REST endpoints.',
        'Deploying full-stack workloads across edge platforms like Cloudflare Workers or serverless Vercel.',
      ],
    },
    avoidWhen: {
      id: [
        'Aplikasi murni SPA statis tanpa kebutuhan SSR atau backend server (gunakan Vite standar + TanStack Router).',
      ],
      en: [
        'Pure static client-only SPAs with no SSR or server-side logic requirements (use plain Vite + TanStack Router).',
      ],
    },
    howItWorks: {
      id: [
        'Mengonfigurasi aplikasi dengan file `app.config.ts`.',
        'Menulis server functions menggunakan `createServerFn({ method: "GET" | "POST" })` dengan validasi payload Zod.',
        'Memanggil server function langsung di dalam loader rute atau event handler komponen dengan inferensi tipe utuh.',
        'Mengkompilasi artifact produksi dan mendeploy sesuai preset Nitro target.',
      ],
      en: [
        'Configures application bundling via `app.config.ts`.',
        'Authors Server Functions via `createServerFn({ method: "GET" | "POST" })` with Zod input validation.',
        'Invokes Server Functions directly inside route loaders or component handlers with full type inference.',
        'Compiles production bundles targeting designated Nitro deployment presets.',
      ],
    },
    coreRules: {
      id: [
        'Pastikan rahasia lingkungan (secret keys) hanya diakses di dalam blok server function atau middleware server.',
        'Validasi selalu parameter input server function dengan skema validator (`.validator(zodSchema)`).',
      ],
      en: [
        'Ensure private secrets are only accessed inside server functions or server middleware.',
        'Always validate Server Function input payloads with schema validators (`.validator(zodSchema)`).',
      ],
    },
    tips: {
      id: [
        'Gunakan middleware chaining untuk menambahkan autentikasi dan otorisasi terpusat pada sekumpulan Server Functions.',
      ],
      en: [
        'Adopt middleware chaining to enforce centralized authentication across clusters of Server Functions.',
      ],
    },
    pairsWellWith: ['tanstack-router', 'tanstack-query', 'cloudflare-workers-access-tunnel'],
    spotlight: {
      title: {
        id: 'Server Functions (RPC): Backend Type-Safe Tanpa API Boilerplate',
        en: 'Server Functions (RPC): Type-Safe Backend Without API Boilerplate',
      },
      body: {
        id: 'Dengan TanStack Start `createServerFn`, batas antara frontend dan backend dijembatani secara elegan. Anda menulis fungsi backend yang langsung memanggil Prisma atau PostgreSQL, dan memanggilnya di komponen React seolah-olah fungsi lokal. Kompiler otomatis memecahnya: kode rahasia tetap berada di server, dan klien hanya menerima RPC endpoint yang 100% type-safe tanpa menulis boilerplate fetch manual.',
        en: 'With TanStack Start `createServerFn`, the boundary between frontend and backend is bridged seamlessly. You author backend logic executing Prisma or PostgreSQL queries, and call it inside React components as if it were a local function. The compiler splits it cleanly: server secrets stay on the server, while the client receives a 100% type-safe RPC proxy without manual fetch boilerplate.',
      },
    },
    sourcePath: 'plugins/tanstack-start/skills/tanstack-start/SKILL.md',
  },
  {
    name: 'tanstack-virtual',
    category: 'performance-ui',
    invocation: 'model',
    description: {
      id: 'Headless virtualization untuk me-render daftar, grid, dan tabel berukuran raksasa pada 60FPS dengan alokasi DOM minimal.',
      en: 'Headless virtualization for rendering massive lists, grids, and tables at 60FPS with minimal DOM allocation.',
    },
    detailedDescription: {
      id: 'Skill optimasi rendering untuk TanStack Virtual (@tanstack/react-virtual). Mengkalkulasi item yang berada dalam viewport layar secara matematis dan hanya me-render elemen yang terlihat ditambah buffer overscan kecil. Mendukung elemen dengan ukuran tetap (fixed) maupun ukuran dinamis yang dihitung saat runtime (dynamic measurement), scroll windowing, infinite loading, serta virtualisasi 2D grid.',
      en: 'Rendering performance skill for TanStack Virtual (@tanstack/react-virtual). Mathematically computes viewport boundaries and renders only elements currently in view plus a narrow overscan buffer. Supports fixed-size items, dynamic runtime DOM measurements, window scrolling, infinite pagination integration, and 2D grid virtualization.',
    },
    useWhen: {
      id: [
        'Menampilkan daftar data berukuran besar (> 1.000 item) yang memperlambat browser jika dirender seluruhnya.',
        'Membangun infinite feed sosial media, chat history, atau log viewer.',
        'Mengvirtualisasi baris dan kolom pada datagrid raksasa bersama TanStack Table.',
      ],
      en: [
        'Displaying massive datasets (> 1,000 items) that cause DOM freezing when rendered completely.',
        'Building infinite feeds, chat streams, or real-time log viewers.',
        'Virtualizing rows and columns inside enterprise datagrids alongside TanStack Table.',
      ],
    },
    avoidWhen: {
      id: [
        'Daftar pendek (< 100 item) di mana overhead virtualisasi tidak sebanding dengan manfaatnya.',
      ],
      en: [
        'Short lists (< 100 items) where virtualization overhead outweighs DOM savings.',
      ],
    },
    howItWorks: {
      id: [
        'Menginisialisasi virtualizer dengan referensi container scroll via `useVirtualizer`.',
        'Mengonfigurasi `count`, `getScrollElement`, dan `estimateSize`.',
        'Merender container total dengan `virtualizer.getTotalSize()` dan memposisikan item aktif secara absolut menggunakan `virtualItem.start`.',
      ],
      en: [
        'Initializes virtualizer instance with container ref via `useVirtualizer`.',
        'Configures `count`, `getScrollElement`, and `estimateSize`.',
        'Renders total space wrapper via `virtualizer.getTotalSize()` and positions active rows via `virtualItem.start`.',
      ],
    },
    coreRules: {
      id: [
        'Container pembungkus wajib memiliki style `overflow: auto` dan tinggi yang terdefinisi secara eksplisit.',
        'Gunakan properti `ref={virtualizer.measureElement}` jika tinggi tiap baris bervariasi secara dinamis.',
      ],
      en: [
        'The scroll parent container must declare `overflow: auto` and have an explicit height.',
        'Attach `ref={virtualizer.measureElement}` on dynamic nodes with variable heights.',
      ],
    },
    tips: {
      id: [
        'Atur `overscan: 5` untuk memuat 5 item ekstra di luar layar agar scrolling cepat tidak memperlihatkan celah putih kosong.',
      ],
      en: [
        'Set `overscan: 5` to render 5 items beyond viewport bounds, preventing blank flickers during fast scrolling.',
      ],
    },
    pairsWellWith: ['tanstack-table', 'tanstack-query'],
    spotlight: {
      title: {
        id: 'Virtualisasi Elemen Dinamis Tanpa Jank',
        en: 'Jank-Free Dynamic Item Virtualization',
      },
      body: {
        id: 'Banyak solusi virtualisasi gagal saat tinggi item tidak seragam (misal tweet dengan lampiran gambar vs tweet teks pendek). TanStack Virtual menyelesaikan ini dengan dynamic element measurement: virtualizer menggunakan estimasi awal, lalu saat elemen dirender ke DOM, `measureElement` mencatat tinggi pixel sesungguhnya dan mengoreksi offset scroll secara instan tanpa lonjakan visual (zero layout jank).',
        en: 'Many virtualization packages stutter when item heights vary (e.g. social posts with media attachments vs text-only posts). TanStack Virtual solves this through dynamic element measurement: it initializes with an estimate, and as elements mount into the DOM, `measureElement` measures actual heights and recalibrates offsets with zero layout jank.',
      },
    },
    sourcePath: 'plugins/tanstack-virtual/skills/tanstack-virtual/SKILL.md',
  },
  {
    name: 'tanstack-store',
    category: 'state-management',
    invocation: 'model',
    description: {
      id: 'Store reaktif imutabel yang framework-agnostic: primitif state ringan mirip signal, derived computed values, batch updates, dan efek.',
      en: 'Framework-agnostic immutable reactive data store: lightweight signal-like state primitives, derived values, batch updates, and effects.',
    },
    detailedDescription: {
      id: 'Skill untuk TanStack Store (@tanstack/store, @tanstack/react-store). Merupakan engine reaktif berbasis imutabel yang menjadi pondasi internal perpustakaan TanStack lainnya. Menyediakan kelas `Store` untuk menyimpan state, `Derived` untuk nilai turunan ter-memoize, `Effect` untuk efek samping reaktif, serta utilitas `batch` untuk menggabungkan banyak mutasi state ke dalam satu notifikasi render tunggal.',
      en: 'Skill for TanStack Store (@tanstack/store, @tanstack/react-store). Lightweight, framework-agnostic reactive immutable state store that powers TanStack internals. Provides `Store` instances for state, `Derived` for memoized computations, `Effect` for reactive side-effects, and `batch` utilities to consolidate multiple state mutations into a single render notification pass.',
    },
    useWhen: {
      id: [
        'Membangun state management global yang ringan tanpa keterikatan ke framework tertentu.',
        'Mengisolasi logika bisnis dan state aplikasi di luar pohon komponen UI React.',
      ],
      en: [
        'Building lightweight global client state without tight coupling to specific frameworks.',
        'Decoupling application business logic and state outside React component trees.',
      ],
    },
    avoidWhen: {
      id: [
        'Mengelola data server asynchronous dari API (gunakan tanstack-query).',
      ],
      en: [
        'Managing asynchronous server data fetched from APIs (use tanstack-query).',
      ],
    },
    howItWorks: {
      id: [
        'Membuat store mandiri `new Store(initialState)`.',
        'Menggunakan selector di dalam komponen React via `useStore(store, selector)`.',
        'Memperbarui state menggunakan `store.setState(updater)`.',
      ],
      en: [
        'Creates autonomous stores via `new Store(initialState)`.',
        'Subscribes with selectors in React components via `useStore(store, selector)`.',
        'Updates state payloads with `store.setState(updater)`.',
      ],
    },
    coreRules: {
      id: [
        'Selalu gunakan selector murni di `useStore` untuk memastikan komponen hanya me-render saat slice data relevan berubah.',
      ],
      en: [
        'Always pass pure selector functions into `useStore` to restrict re-renders to touched data slices.',
      ],
    },
    tips: {
      id: [
        'Bungkus pembaruan beruntun di dalam `batch(() => { ... })` untuk menghindari lonjakan render ganda.',
      ],
      en: [
        'Wrap sequential mutations inside `batch(() => { ... })` to avoid duplicate render sweeps.',
      ],
    },
    pairsWellWith: ['tanstack-router', 'tanstack-form'],
    spotlight: {
      title: {
        id: 'Framework-Agnostic Core: Berbagi Logika Lintas UI',
        en: 'Framework-Agnostic Core: Logic Sharing Across UI Layers',
      },
      body: {
        id: 'TanStack Store dirancang murni TypeScript tanpa dependensi React. Anda dapat menulis modul logika bisnis, store e-commerce, atau game loop satu kali di file TypeScript mandiri, lalu menyambungkannya ke React via `@tanstack/react-store`, ke Solid via `@tanstack/solid-store`, atau bahkan berjalan di backend Node.js tanpa modifikasi kode.',
        en: 'TanStack Store is engineered in pure TypeScript with zero React dependencies. You can author business logic, state machines, or cart stores once in vanilla TypeScript, then connect it to React via `@tanstack/react-store`, Solid via `@tanstack/solid-store`, or run it on Node.js backends with zero code divergence.',
      },
    },
    sourcePath: 'plugins/tanstack-store/skills/tanstack-store/SKILL.md',
  },
  {
    name: 'tanstack-ai',
    category: 'ai-sdk',
    invocation: 'model',
    description: {
      id: 'SDK AI modular dan type-safe yang provider-agnostic: streaming teks, pemanggilan alat (tool calling) dengan approval workflow, structured output Zod, dan hooks UI.',
      en: 'Provider-agnostic modular type-safe AI SDK: text streaming, tool calling with approval workflows, Zod structured outputs, and UI hooks.',
    },
    detailedDescription: {
      id: 'Skill arsitektur integrasi AI modern untuk TanStack AI (@tanstack/ai). Menyediakan adapter modular yang dapat di-tree-shake untuk berbagai provider LLM (OpenAI, Anthropic, Gemini, Ollama). Menangani streaming response tingkat rendah, eksekusi function/tool calling dengan antrean persetujuan (approval gates), parsing output JSON terstruktur yang tervalidasi skema Zod, dukungan multimodal teks/gambar, serta hooks React untuk antarmuka percakapan chat dan generative UI.',
      en: 'Modern AI architecture skill for TanStack AI (@tanstack/ai). Features tree-shakeable adapters across major LLM providers (OpenAI, Anthropic, Gemini, Ollama). Manages low-level response streaming, function/tool calling execution with human-in-the-loop approval gates, Zod schema-enforced structured JSON output parsing, multimodal media pipelines, and React hooks for interactive chat and generative UI experiences.',
    },
    useWhen: {
      id: [
        'Membangun fitur AI chat, generative UI, atau agent workflows di aplikasi React/TypeScript.',
        'Menerapkan tool calling aman dengan alur persetujuan pengguna (human-in-the-loop).',
        'Mengekstrak data terstruktur dari model AI dengan validasi skema Zod yang ketat.',
      ],
      en: [
        'Building interactive AI chat, generative UI, or agent pipelines in React/TypeScript.',
        'Enforcing safe tool calling with human-in-the-loop approval workflows.',
        'Extracting structured data from LLMs with strict Zod schema validation.',
      ],
    },
    avoidWhen: {
      id: [
        'Aplikasi sederhana yang hanya memanggil endpoint completion statis tanpa streaming atau tool calling.',
      ],
      en: [
        'Simple applications executing single static completions with no streaming or tool calls.',
      ],
    },
    howItWorks: {
      id: [
        'Mengonfigurasi client dengan adapter provider yang dipilih (misal OpenAI atau Anthropic).',
        'Mendefinisikan tools dengan nama, deskripsi, skema parameter Zod, dan fungsi eksekutor.',
        'Menggunakan hook `useChat` atau `useCompletion` untuk streaming token dan status interaksi.',
      ],
      en: [
        'Configures AI client with designated provider adapters (e.g. OpenAI, Anthropic).',
        'Declares tools with typed names, descriptions, Zod schemas, and executor callbacks.',
        'Binds chat UI state via `useChat` or `useCompletion` for token streaming and status tracking.',
      ],
    },
    coreRules: {
      id: [
        'Selalu tentukan skema Zod pada parameter alat (tools) agar argumen dari LLM divalidasi sebelum dieksekusi.',
        'Sediakan fallback penanganan error saat koneksi streaming terputus di tengah jalan.',
      ],
      en: [
        'Always provide strict Zod schemas on tool parameters to validate LLM inputs prior to execution.',
        'Provide robust error recovery handlers for interrupted streaming network connections.',
      ],
    },
    tips: {
      id: [
        'Gunakan approval workflow bawaan untuk perkakas sensitif (misal eksekusi pembayaran atau penghapusan data).',
      ],
      en: [
        'Leverage built-in approval workflows for high-risk operations (e.g. billing actions, data deletions).',
      ],
    },
    pairsWellWith: ['tanstack-start', 'tanstack-form'],
    spotlight: {
      title: {
        id: 'Human-in-the-Loop Tool Calling Built-in',
        en: 'Built-in Human-in-the-Loop Tool Calling',
      },
      body: {
        id: 'Banyak SDK AI mengeksekusi function calling secara otomatis di background tanpa konfirmasi. TanStack AI memiliki mekanisme persetujuan kelas satu: alat dapat dideklarasikan membutuhkan konfirmasi pengguna. Eksekusi akan dijeda (paused), UI merender tombol persetujuan, dan fungsi baru dieksekusi setelah pengguna mengonfirmasi, mencegah agen melakukan aksi destruktif tanpa izin.',
        en: 'Many AI libraries execute tool calls automatically in the background without user oversight. TanStack AI introduces first-class approval workflows: sensitive tools pause execution, render confirmation controls into the UI, and only execute upon explicit user approval, preventing autonomous agents from running destructive mutations unprompted.',
      },
    },
    sourcePath: 'plugins/tanstack-ai/skills/tanstack-ai/SKILL.md',
  },
  {
    name: 'tanstack-db',
    category: 'client-database',
    invocation: 'model',
    description: {
      id: 'Database tertanam sisi klien berbasis differential dataflow: koleksi ternormalisasi, live reactive queries, dan mutasi optimis instan.',
      en: 'Embedded client-side database powered by differential dataflow: normalized collections, live reactive queries, and instant optimistic mutations.',
    },
    detailedDescription: {
      id: 'Skill untuk TanStack DB (@tanstack/react-db). Menempatkan lapisan database reaktif di memori browser yang didukung algoritma differential dataflow. Mengelola koleksi data ternormalisasi, mengeksekusi kueri langsung (live queries) yang terbarui secara inkremental dalam sub-milidetik bahkan pada 100.000+ baris data, serta terintegrasi mulus dengan TanStack Query untuk sinkronisasi backend.',
      en: 'Skill for TanStack DB (@tanstack/react-db). Deploys an in-memory client-side database layer powered by differential dataflow. Maintains normalized collections, runs incremental live reactive queries updating in sub-milliseconds across 100k+ rows, and integrates natively with TanStack Query for backend synchronization.',
    },
    useWhen: {
      id: [
        'Membangun aplikasi web local-first atau offline-capable dengan dataset besar di memori browser.',
        'Membutuhkan kueri live kompleks (filter multi-relasi) yang harus terbarui instan tanpa beban render berat.',
      ],
      en: [
        'Engineering local-first or offline-capable applications with heavy in-memory client datasets.',
        'Executing complex live queries across collections updating in sub-milliseconds.',
      ],
    },
    avoidWhen: {
      id: [
        'Aplikasi sederhana dengan kebutuhan data fetching standar (gunakan tanstack-query).',
      ],
      en: [
        'Standard applications with conventional request-response data requirements (use tanstack-query).',
      ],
    },
    howItWorks: {
      id: [
        'Mendefinisikan skema koleksi dan indeks pada client DB.',
        'Memuat data awal dan menghubungkannya dengan sinkronisasi TanStack Query.',
        'Mengeksekusi live query di komponen yang otomatis terbarui saat record diubah.',
      ],
      en: [
        'Defines collection schemas and primary indexes on the client database.',
        'Loads initial datasets and binds synchronizers to TanStack Query.',
        'Subscribes to live queries inside components updating automatically on record mutation.',
      ],
    },
    coreRules: {
      id: [
        'Pastikan setiap record memiliki primary key unik yang stabil.',
      ],
      en: [
        'Ensure every record possesses a stable, unique primary key.',
      ],
    },
    tips: {
      id: [
        'Gunakan `@tanstack/query-db-collection` untuk sinkronisasi otomatis antara backend API dan koleksi lokal.',
      ],
      en: [
        'Use `@tanstack/query-db-collection` to automate synchronization between remote APIs and local collections.',
      ],
    },
    pairsWellWith: ['tanstack-query', 'tanstack-table'],
    spotlight: {
      title: {
        id: 'Differential Dataflow di Memori Klien',
        en: 'Client-Side Differential Dataflow',
      },
      body: {
        id: 'Alih-alih menyaring ulang seluruh array 100.000 item setiap kali ada satu data yang berubah, engine TanStack DB hanya menghitung selisih matematis (delta). Komputasi kueri selesai dalam pecahan milidetik tanpa membebani thread utama JavaScript.',
        en: 'Instead of re-filtering an entire 100,000-item array whenever a single record updates, TanStack DB only calculates mathematical deltas. Live queries update in sub-milliseconds without blocking the browser main thread.',
      },
    },
    sourcePath: 'plugins/tanstack-db/skills/tanstack-db/SKILL.md',
  },
  {
    name: 'tanstack-devtools',
    category: 'developer-tools',
    invocation: 'model',
    description: {
      id: 'Panel devtools terpadu untuk perpustakaan TanStack: inspeksi status real-time, arsitektur plugin modular, dan debugging visual.',
      en: 'Unified extensible devtools panel for TanStack libraries: real-time state inspection, modular plugin architecture, and visual debugging.',
    },
    detailedDescription: {
      id: 'Skill untuk TanStack Devtools (@tanstack/react-devtools). Mengonsolidasikan panel debugging untuk TanStack Query, Router, Form, dan library lainnya ke dalam satu floating panel terpadu. Dibangun dengan Solid.js untuk performa ultra-ringan tanpa membebani lifecycle render aplikasi host.',
      en: 'Developer tool skill for TanStack Devtools (@tanstack/react-devtools). Consolidates debugging panels for TanStack Query, Router, Form, and other ecosystem tools into a single extensible panel. Built with Solid.js for lightweight performance with zero render interference on host apps.',
    },
    useWhen: {
      id: [
        'Melakukan debugging status cache query, transisi rute, atau validasi form saat tahap pengembangan.',
      ],
      en: [
        'Debugging query cache lifecycles, route transitions, or form validation during development.',
      ],
    },
    avoidWhen: {
      id: [
        'Build produksi (devtools otomatis dihilangkan pada bundle production).',
      ],
      en: [
        'Production builds (devtools are automatically stripped from production bundles).',
      ],
    },
    howItWorks: {
      id: [
        'Mengimpor dan merender komponen devtools hanya pada lingkungan `process.env.NODE_ENV === "development"`.',
      ],
      en: [
        'Imports and mounts devtools components conditionally in development environments.',
      ],
    },
    coreRules: {
      id: [
        'Pastikan devtools tidak dimasukkan ke dalam bundle akhir produksi.',
      ],
      en: [
        'Ensure devtools are excluded or tree-shaken from production deployments.',
      ],
    },
    tips: {
      id: [
        'Buka tab Router Devtools untuk memeriksa status rute aktif, params, dan riwayat loader secara visual.',
      ],
      en: [
        'Open Router Devtools to inspect active route states, params, and loader timelines visually.',
      ],
    },
    pairsWellWith: ['tanstack-router', 'tanstack-query'],
    spotlight: {
      title: {
        id: 'Isolasi Solid.js: Bebas Efek Samping Render',
        en: 'Solid.js Runtime Isolation: Zero Host Interference',
      },
      body: {
        id: 'TanStack Devtools dibangun menggunakan Solid.js mandiri. Ini menjamin bahwa inspeksi state dan animasi panel devtools tidak memicu siklus render ulang palsu pada aplikasi React utama yang sedang Anda debug.',
        en: 'TanStack Devtools is engineered with Solid.js. This guarantees panel animations and state inspections never trigger artificial re-renders in the host React application you are actively debugging.',
      },
    },
    sourcePath: 'plugins/tanstack-devtools/skills/tanstack-devtools/SKILL.md',
  },
  {
    name: 'tanstack-cli',
    category: 'cli-tooling',
    invocation: 'model',
    description: {
      id: 'CLI scaffolding aplikasi TanStack Start: 30+ integrasi bawaan, template kustom tim, dan MCP server untuk coding agent.',
      en: 'Project scaffolding CLI for TanStack Start: 30+ pre-built integrations, custom team templates, and MCP server for coding agents.',
    },
    detailedDescription: {
      id: 'Skill untuk TanStack CLI (@tanstack/cli). Memandu pembuatan proyek TanStack Start interaktif dengan 30+ integrasi siap pakai (database, autentikasi, styling, hosting). Dilengkapi MCP (Model Context Protocol) server bawaan yang memungkinkan agen AI seperti Hermes, Claude Code, dan Cursor membantu konfigurasi proyek secara otomatis.',
      en: 'Skill for TanStack CLI (@tanstack/cli). Guides interactive scaffolding of TanStack Start projects with 30+ pre-configured integrations (databases, auth, styling, hosting). Features a built-in MCP (Model Context Protocol) server enabling AI agents like Hermes, Claude Code, and Cursor to scaffold and modify projects autonomously.',
    },
    useWhen: {
      id: [
        'Membuat proyek baru berbasis TanStack Start dengan setup database dan auth instan.',
        'Menjalankan TanStack MCP server untuk membantu coding agent memahami konfigurasi.',
      ],
      en: [
        'Scaffolding greenfield TanStack Start projects with instant database and auth presets.',
        'Running the TanStack MCP server to assist coding agents with project configuration.',
      ],
    },
    avoidWhen: {
      id: [
        'Proyek yang sudah berjalan stabil dan tidak memerlukan pembuatan struktur baru.',
      ],
      en: [
        'Established projects with mature architectures requiring no scaffolding.',
      ],
    },
    howItWorks: {
      id: [
        'Menjalankan `npm create @tanstack/app` dan memilih preset integrasi.',
      ],
      en: [
        'Executes `npm create @tanstack/app` and selects integration presets.',
      ],
    },
    coreRules: {
      id: [
        'Gunakan Node.js 20+ saat menjalankan TanStack CLI scaffolding.',
      ],
      en: [
        'Require Node.js 20+ when executing TanStack CLI scaffolding.',
      ],
    },
    tips: {
      id: [
        'Pilih template terintegrasi Prisma atau Supabase untuk mendapatkan konfigurasi full-stack instan.',
      ],
      en: [
        'Select Prisma or Supabase integrated templates for instant full-stack setup.',
      ],
    },
    pairsWellWith: ['tanstack-start', 'prisma-database-setup'],
    spotlight: {
      title: {
        id: 'Integrasi MCP Bawaan untuk Coding Agent',
        en: 'Built-in MCP Server for Coding Agents',
      },
      body: {
        id: 'TanStack CLI menyertakan server MCP (Model Context Protocol) resmi. Agen AI Anda dapat berkomunikasi langsung dengan CLI untuk menanyakan dependensi yang cocok, memvalidasi konfigurasi, dan menambahkan integrasi baru tanpa trial-and-error manual.',
        en: 'TanStack CLI embeds an official MCP (Model Context Protocol) server. Your AI coding agent can query the CLI directly to inspect compatible dependencies, validate configurations, and wire integrations without manual guesswork.',
      },
    },
    sourcePath: 'plugins/tanstack-cli/skills/tanstack-cli/SKILL.md',
  },
  {
    name: 'tanstack-config',
    category: 'tooling-monorepo',
    invocation: 'model',
    description: {
      id: 'Toolkit monorepo dan penerbitan paket TypeScript: build Vite minimal-konfigurasi, preset ESLint, versi semantik, dan Changesets.',
      en: 'Toolkit for TypeScript package development and publishing: zero-config Vite builds, ESLint presets, semantic versioning, and Changesets.',
    },
    detailedDescription: {
      id: 'Skill untuk TanStack Config (@tanstack/config). Toolkit standar yang digunakan tim inti TanStack untuk membangun, menguji, dan menerbitkan paket JavaScript/TypeScript modern. Mengatur monorepo pnpm/Nx, build multi-target (ESM/CJS), integrasi Changesets untuk rilis versi otomatis, dan verifikasi CI.',
      en: 'Skill for TanStack Config (@tanstack/config). The official opinionated toolkit used by the TanStack core team to author, compile, and publish modern JS/TS libraries. Standardizes pnpm/Nx monorepos, multi-target builds (ESM/CJS), Changesets automated publishing, and CI checks.',
    },
    useWhen: {
      id: [
        'Membangun open-source library TypeScript atau mengelola monorepo package modern.',
      ],
      en: [
        'Developing open-source TypeScript packages or managing modern library monorepos.',
      ],
    },
    avoidWhen: {
      id: [
        'Aplikasi web consumer biasa yang bukan merupakan library reusable.',
      ],
      en: [
        'Standard end-user web applications that are not reusable libraries.',
      ],
    },
    howItWorks: {
      id: [
        'Mengonfigurasi skrip build dan konfigurasi monorepo mengikuti konvensi resmi TanStack.',
      ],
      en: [
        'Configures build pipelines and monorepo configs matching official TanStack conventions.',
      ],
    },
    coreRules: {
      id: [
        'Pastikan file deklarasi tipe `.d.ts` selalu di-generate saat build library.',
      ],
      en: [
        'Ensure `.d.ts` type declarations are always emitted during library compilation.',
      ],
    },
    tips: {
      id: [
        'Gunakan Changesets untuk melacak perubahan fitur dan menghasilkan changelog otomatis.',
      ],
      en: [
        'Adopt Changesets to track semantic version bumps and generate automated changelogs.',
      ],
    },
    pairsWellWith: ['tanstack-router', 'tanstack-store'],
    spotlight: {
      title: {
        id: 'Standar Penerbitan Paket Modern TanStack',
        en: 'The Modern TanStack Package Publishing Standard',
      },
      body: {
        id: 'Membangun paket modern yang kompatibel dengan ESM, CommonJS, bundler Vite, dan TypeScript NodeNext sering membingungkan. TanStack Config mengotomatisasi pemetaan `package.json` `exports` yang benar sehingga library Anda dapat diimpor tanpa masalah module resolution di lingkungan mana pun.',
        en: 'Crafting modern packages compatible across ESM, CommonJS, Vite, and TypeScript NodeNext is notoriously difficult. TanStack Config standardizes precise `package.json` `exports` maps ensuring libraries resolve cleanly in any runtime environment.',
      },
    },
    sourcePath: 'plugins/tanstack-config/skills/tanstack-config/SKILL.md',
  },
  {
    name: 'tanstack-pacer',
    category: 'timing-utilities',
    invocation: 'model',
    description: {
      id: 'Utilitas pengaturan waktu eksekusi fungsi yang type-safe: debouncing, throttling, rate limiting, antrean queue, dan batching.',
      en: 'Type-safe function execution timing toolkit: debouncing, throttling, rate limiting, queues, and batching.',
    },
    detailedDescription: {
      id: 'Skill untuk TanStack Pacer (@tanstack/pacer, @tanstack/react-pacer). Menyediakan kontrol presisi atas frekuensi eksekusi fungsi JavaScript: debounce input pencarian, throttle event scroll/resize, rate limiting panggilan API pihak ketiga, antrean eksekusi berurutan (queues), dan pengelompokan panggilan ganda menjadi satu batch.',
      en: 'Skill for TanStack Pacer (@tanstack/pacer, @tanstack/react-pacer). Delivers unified, type-safe execution timing control: search input debouncing, scroll/resize event throttling, external API rate limiting, sequential execution queues, and batched call aggregation.',
    },
    useWhen: {
      id: [
        'Mengontrol frekuensi panggilan fungsi pada input teks interaktif atau event scroll.',
        'Menerapkan rate limiting atau queue pemrosesan tugas pada sisi klien.',
      ],
      en: [
        'Regulating function execution rates on interactive text inputs or scroll events.',
        'Enforcing client-side rate limiting or serialized task queues.',
      ],
    },
    avoidWhen: {
      id: [
        'Fungsi sinkron sederhana yang tidak memerlukan penundaan atau pengendalian frekuensi.',
      ],
      en: [
        'Simple synchronous functions requiring zero timing constraints.',
      ],
    },
    howItWorks: {
      id: [
        'Menggunakan kelas pacer atau React hook `useDebounce` / `useThrottle` dengan interval waktu yang ditentukan.',
      ],
      en: [
        'Applies pacer classes or React hooks (`useDebounce`, `useThrottle`) with specified millisecond timings.',
      ],
    },
    coreRules: {
      id: [
        'Batalkan timer pacer yang masih berjalan saat komponen di-unmount untuk mencegah memory leak.',
      ],
      en: [
        'Cancel pending timers on component unmount to prevent dangling memory leaks.',
      ],
    },
    tips: {
      id: [
        'Gunakan batching pacer untuk mengumpulkan 10 event klik atau log analitik ke dalam satu request jaringan.',
      ],
      en: [
        'Use batching pacers to bundle rapid click events or telemetry pings into a single network payload.',
      ],
    },
    pairsWellWith: ['tanstack-table', 'tanstack-query'],
    spotlight: {
      title: {
        id: 'Kontrol Timing Fungsi yang Terpadu dan Type-Safe',
        en: 'Unified, Type-Safe Function Timing Control',
      },
      body: {
        id: 'Banyak proyek mencampur library lodash.debounce, p-limit, dan timeout manual yang rentan memory leak. TanStack Pacer menyatukan seluruh pola pengaturan waktu (debounce, throttle, queue, batch) ke dalam API modern bertipe TypeScript kuat dengan pembatalan otomatis.',
        en: 'Teams often combine disparate packages like lodash.debounce, p-limit, and manual timeouts prone to dangling references. TanStack Pacer unifies all timing disciplines (debounce, throttle, queue, batch) under one type-safe API with automatic teardown.',
      },
    },
    sourcePath: 'plugins/tanstack-pacer/skills/tanstack-pacer/SKILL.md',
  },
  {
    name: 'tanstack-ranger',
    category: 'headless-ui',
    invocation: 'model',
    description: {
      id: 'Utilitas headless untuk membangun slider rentang nilai tunggal dan multi-range yang sepenuhnya dapat diakses.',
      en: 'Headless utilities for building fully accessible single-value and multi-thumb range sliders.',
    },
    detailedDescription: {
      id: 'Skill untuk TanStack Ranger (@tanstack/react-ranger). Menyediakan seluruh perhitungan matematika dan status interaksi untuk komponen slider rentang harga, filter batas nilai, dan multi-thumb range picker. Bekerja secara headless tanpa style atau markup bawaan.',
      en: 'Skill for TanStack Ranger (@tanstack/react-ranger). Encapsulates all mathematical boundary calculations and interaction states for range sliders, price filter boundaries, and multi-thumb controls. Functions purely headlessly with complete styling freedom.',
    },
    useWhen: {
      id: [
        'Membangun komponen slider interaktif (misal filter harga produk e-commerce min-max).',
      ],
      en: [
        'Building custom range sliders (e.g. e-commerce min-max price filters).',
      ],
    },
    avoidWhen: {
      id: [
        'Input angka numerik standar yang cukup menggunakan `<input type="number" />`.',
      ],
      en: [
        'Standard numeric inputs where `<input type="number" />` is sufficient.',
      ],
    },
    howItWorks: {
      id: [
        'Memanggil hook `useRanger` dengan nilai `min`, `max`, `stepSize`, dan array `values`.',
        'Merender track container dan thumb slider menggunakan properti posisi persentase yang dihitung Ranger.',
      ],
      en: [
        'Invokes `useRanger` passing `min`, `max`, `stepSize`, and current `values`.',
        'Renders track containers and thumbs using percentage coordinates calculated by Ranger.',
      ],
    },
    coreRules: {
      id: [
        'Pastikan atribut aksesibilitas ARIA (`aria-valuemin`, `aria-valuemax`, `aria-valuenow`) disematkan pada handle thumb.',
      ],
      en: [
        'Ensure accessible ARIA attributes (`aria-valuemin`, `aria-valuemax`, `aria-valuenow`) are mapped to thumb nodes.',
      ],
    },
    tips: {
      id: [
        'Gunakan Tailwind CSS untuk memberikan styling visual halus pada track dan thumb slider.',
      ],
      en: [
        'Use Tailwind CSS to style custom thumb grabbers and track accent colors.',
      ],
    },
    pairsWellWith: ['tanstack-form', 'tanstack-table'],
    spotlight: {
      title: {
        id: 'Multi-Thumb Slider dengan Aksesibilitas Penuh',
        en: 'Accessible Multi-Thumb Range Sliders',
      },
      body: {
        id: 'Membangun slider dua handle (min-max) dari nol sangat rumit dalam hal penanganan tab keyboard dan tabrakan handle. TanStack Ranger mengelola matematika posisi dan navigasi tombol panah keyboard secara otomatis, memungkinkan developer cukup memikirkan tampilan visualnya.',
        en: 'Authoring dual-thumb (min-max) sliders from scratch is notoriously complex regarding keyboard navigation and thumb collision. TanStack Ranger computes bounding physics and keyboard arrow events automatically, letting you focus entirely on design.',
      },
    },
    sourcePath: 'plugins/tanstack-ranger/skills/tanstack-ranger/SKILL.md',
  },
]
